* <2021-02-28 Sun>     10. 黒切り

        しずこが奉公する十年前に大井で事故が起こっていた。

        各部落で共用の山地や水溝の整備のために各家庭から作業員を出すことになっている。
        その中のひとつである黒切りが春の浅い日に行われた。
        いつもなら男手を出す予定だったがその日は牛の競のため
        まさおは現在宗像消防署がある場所に立っていた畜産市場に行っていた。
        仕方ないので嫁のしんが黒切りの作業に山に入っていた。
        出方を出さないとペナルティーを課せられるしくみだったので止むを得ない状況だった。

        運の悪く母親がまだ恋しい10歳のやすおが学校から帰宅したところ母親がいないので兄たちに聞くと
        山に黒切りに行っているということなので兄たち一緒に遊びがてら山に入っていった。
        小高い丘の上に立つ５軒の茅葺屋根の民家があってその横を抜けると孟宗竹の林が
        たちこめゆっくりと山の中腹に入る道が現れる３人の子供は慣れた足付きで黒切り
        の作業場を探したがもっと奥で作業しているらしい。
       
        大井の田園がひろがる道の横に水神様と里の人が呼ぶ小さな池がある。
        今は朽ちているがレンガで囲いの残骸がありその周囲には２・３本の松と1本の柳の木があった。
        この柳の木を切ると怪我人がでるとか死人がでるとかの言い伝えがあって、
        部落のだれもが知っている。
        今年の初冬その柳が枯れた。

        やすおは母を追って山に入ったが兄や弟に置いていかれて不安を覚えていた。
        ４月とはいえ深い木立に空さえ遮られているので肌寒い。ふと横に目をやると小さな水の
        流れを発見した。蟹や魚がいるかもしれない。その流れを隠すように大きな岩があったので
        それによじ登って覗こうとした。
        登り終えたと同じに岩が崩れてやすおは放り出されてその岩の下敷きになった。
        やすおの叫び声と石が重い音を立てるを聞いた兄と弟は駆け寄ってやすおが岩の下敷き
        なっているのを見つけた。
        弟のかつおはなすすべなく立ち尽くし「かあーちゃん」と泣きさけんだ。
        兄のとしおは大人を探すべく山を登って行ってほどなくして大人を数人つれてきた。
        大人は木の枝を切ってテコでなんとかやすおを引き出したがやすおは絶命していた。
        兄のとしおは再び母親を伴って現れた。
        母は泣き崩れた。
        やすおは学校で一番の頭の良さでだれもが認めるような神童だった。
        特に算数はずば抜けていてたびたび先生を驚かせていた。
        なんでもすぐに理解できオルガンも教えてもらえなくとも弾くことができた。
        生徒はそのマジックに驚いてやすおはうわさの渦中にもあった。
        やすおの目は透き通っていて眉は太く大きくきりりと終端を勇しくピンと上げて
        天性の才能と華奢なはかなさが女子生徒には憧れになっていた。
        ただ薄幸な唇は悲しさを漂わせていたがその隙間から白い歯がのぞむと
        多くの女生徒はこの男を自分のものにしたいと願っていた。

        母親の口癖は「うちらは人前のことはできん」だった。 
        兄はとしおと言って、弟はかつおと言った。
        彼らが乞食兄弟である。そしてその３番目の兄弟が死んだ。
        この兄弟は男ばかり６人の兄弟であった。
        母は山形県米沢市の生まれである、かの上杉鷹山に使えた中級武士の子孫として
        姉ひとりの二人姉妹として育った。
        家督を相続したいと山形県置賜郡佐沢から婿養子を迎えた。
        明治後半から武士の子として埃はあったが家は極貧しており山形の冬の厳しさ
        から逃がれたいと渇望していた。
        妹のしんは山形でまもなく３人の男の子を授かったが兄ふたりとも病気で夭折させてしまった。
        奇妙なことに３人目の子供を産み下ろした同じ日に父をなくした。
        1934-5-7のことである。父の命日を誕生日にもらった子供がこの乞食兄弟の兄としおである。
       
        しんは極貧の厳しさと偶然に翻弄され胃潰瘍を患って痩せ細っていた。
        亭主は鈍感だがやさしく働き者だったがいっこうに極貧の生活は改善されず、
        二人の子供も失って絶望していた、そんな中姉は男好きのする女で器量も立つので
        男をあてに福岡のこの地に流れ着いていた。
        そして妹の不幸を嘆いてこの地に呼び寄せていたのだ。
        残った一人の５歳の息子をつれて姉を頼ってこの地についていた。
        この大井で200円で家と牛を買って借りた田畑で作物を作り、北九州の黒崎に行商した。
        宗像では３人の男の子をもうけた。都合４人の男の子の兄弟ができた。
        そして今日10歳を迎えた子供を奪われ３人の兄弟になったのだ。
        遺体を家に運んでいつも寝ている汚い布団に寝かせた。近所の夫人会が東郷から医者を呼んで
        警察の対応を済ませてくれた。母親は寝かせた布団の横で首を垂れすすり泣いていた。
        その時育てた牛を売って思わぬ程の収入を得た夫のまさおが帰ってきた。
        まさおは家の前に止まっている警察車両や出入りする近所の人を見てあたふたしたが
        としおとかつおが駆け寄ってきたのでやすおがいないことをわかった。
        「やすおが死んだのか」と呟いた。
        近所のしんぺいが説明して座敷へと寄り添って連れてきた。
        しんは帰ってきた夫を見上げて「なんであんたが黒切りにいかんやった!」と
        責め立てて泣き伏せた。
        割烹着姿の婦人会たちからもすすり泣く声が聞こえた。
        まさおは泣き叫び伏せて震えるしんの肩に手をやってやすおの枕元に座った。
        やすおの顔伏せの白い布をとって顔をなでまわして言った。

        「朝はあげん元気やった。もう好きな餅もくえんとじゃな。」

        1945年浅い春のとてもいい天気の夕刻のことだった。

        東京大空襲の噂は部落に広まって、日本は負けるそんな情勢の中の出来事だった。
        現実として住民をさらに憔悴させたのは６月の福岡大空襲で福岡市の４分の1以上が消失していたことだった。
        疎開して親類のあるこの部落のだれぞのかの噂しかなかったがこの平穏な村でもB52の唸る
        爆音を聞くことがあったので村の人々にも暗雲な不安が広がっていた。
        そしていよいよ不安を増したこの家族にはどん底だったが、それはまだどん底ではなかった。
        1945-8-6 広島と1945-8-9 長崎に落ちたものがなんなのか東郷の居酒屋などで話題にでるが
        だれもわからなかった。
        ??? GHQ 1945-9-19言論統制のためのプレスコード発令

        生まれて５歳になった末っ子のただおはだれよりもまさおに似ていた。
        まさおは食うことがが心情の男だった、山形県東置賜群の佐沢で三男として生まれ
        食い扶持減らしで米沢の通町のしんの婿養子になった。
        手先が器用で竹細工やら庭づくりやら盆栽の手入れなど周りが驚く程の才能を見せていた。
        末っ子のただおはしんとまさおに特に可愛がられた。
        やすおの事故の反動もあったのかもしれないがとにかく二人はただおを可愛がった。
        まさおはしんを愛していたというよりは尊敬の念さえもっていた、気丈な性格、
        すっきりした顔立ちから発する声とその音の散りばめられた空鍋に蓋の水滴が弾いたような
        声のかすれの中に飛び出すとても心地よくかつ怪訝でもありその飛沫の煌めき奥のごく
        弱いがはっきり私に信頼と日本がどう動いてもいい性欲こそが新しい命を繋げてくれる。

        しんは知っていた。ただおとそれを愛すためのものがこの世の中で大勢の中でも二人の
        愛は今後の家庭で収入も上がっていく、牛の選びはよいしあと６ヶ月かければこの牛は
        ２倍の売値をつげるだろう。牛のビジネスにのぞみが出てきて少し生活は楽に向かいそうに見えた。

        やすおの49日が終わる頃学校から帰ってきたただおは母親に腹痛と吐き気を訴えてた、額から汗が滲んでいたため
        急遽往診を呼んだ。医者は赤痢の疑いがあるので和歌の病院につれていくように進めた。
        ??? ここはつながっってない
        夫婦で火病院(??火病院のじが間違っている)にただおをだきはこんだ。

        看護師はたらいに乳白色の洗浄剤を作って家族全員に手をあらわせて、念のため
        病院で全員の検査を行うように段取りをとりつけた。
        幸い家族には感染者は出ず、ただおだけが入院隔離となった。

        暑い夏がきた。
        1945年5月20日～23日は10°まで下がるという稀な初夏の気象だったので尚更この暑い夏が不気味だった。

        火病院へは歩いて20分だったが感染症がゆえ面会は拒絶された、受付で看護師を
        よんで様子を聞くだけだった。衣類も食料も渡すことはできなかった。
        1945-8-13ポツダム宣言受諾の前日に病院により電話がありただおは危篤と知らせ
        がきた。その夜同時に火葬にしたのでお骨を取りにこいと連絡が入った。
        ??? 1964-6から有線電話放送が各家庭に配布だから電話はない、区長宅設置の黒電話のからの人による伝達としてよいかも
        再びこの家族は鎮痛な葬式を迎えることになった。
        やすおと違ってすでにお骨となったただおが仏壇に置かれていた。
        そのまま通夜が家族で行われた。
        翌日の正午のサイレンがならされ公民館には村の民が押しかけていた。
        玉院放送を聞くためだった。
        ??? この描写だれかに聞いてもっと現実味をだせないかな
        その夜、まさおとしんの両親、としおとかつおの兄弟二人、
        ４人の家族はいい知れない不幸に諦めを噛み締めて抱き合って寝た。

        暑い夜にすり減り黄色がかった濃緑色の吊るした蚊帳と蛾のまとわる薄暗い電灯だけがこの家族を守っていた。

        この時期さがせばどこにもこのような不幸は存在した。
        水神様の柳が枯れたから起こったと言いふらすものもいた。
        この話は隣村の用山村でも伝えられた。そして10年たってもしずこにまで届いていた。
