* <2021-02-28 Sun> 7. 八百重屋敷2

  　ななみは自分がどこにいるのかわかってきた修学旅行の最中だったのだ。

  新型コロナの影響で熊本の近県である福岡県に決まった時全校生はため息にどよめいた。

  熊本をバス４台で朝９時に出発し九州高速道路を門司インターまで走らせたついたのが１０時すぎだった。

  　北九州の門司港レトロタウンを散策するまえ九州鉄道博物館を順回していたが展示された蒸気機関車C591の客車に回った時対面の席に背もたれと座席の間に
  埋めっている指輪を見つけた、その指輪を認めた時から時間を遡ってはやくも67年ほどタムスリップしているのだ。

  　二人の姉妹がだれかもわかっているばあちゃんとばあちゃんの姉の二人だ。

  ななみには未来からきたことでこの世界は歴史の趨勢からみても生活はかなり落ちるものだと思っていた。

  しかしここの生活はいきなり他国にいくほどのギャップがあった。

  物理的な有利はほとんどなく、しょうこより２つ年下ゆえの下っ端としてしか扱われないこともわかっていた。

  昨日勉強していたのは安土桃山だったから全然やくにたたない。

  　屋敷の大方人たちはの作業にで払ったあとで女主人と朝食の片付け昼飯の準備で何人かのおなご衆が残っていた。

  　玄関を開けて姉が奥に入り女主人を連れてきた。小さな素朴な顔をした女だったがかぶとい声を使って「遠いところ良くきたね」と労い。

  姉は「いとこがひとり増えた」といったが知り合いにおなご衆をもとめているものはおおいので安心するように言い払った。

  姉に部屋についって着替えて昼食の準備を一緒するようにいった。

  おなご衆の部屋は２階にあった、大きな土間と板間の横の階段を軋ませてあるくと一番奥に部屋があった。

  姉が先に入ると二人のおなご衆が小さな台を挟んで休んでいた。

  姉より年上の二人はなつとふみといった。

  妹といとこを紹介するとさもない冗談をいって笑いが一瞬湧立ったがその後は静かになった。

  なつが「鹿児島はもう暑いのか」と尋ねたが、しょうこは「寒い」と答えて、風呂敷の中からおみやげのカルカンを取り出した。

  そして姉に二つ渡した。

  しょうこを送り出す時その長男が地元の日豊本線加治木駅のキヨスクでカルカンのみやげを二つ持たせてあったのだ。

  ふみが「またカルカンか」といってしずこから取り上げた。

  ふみは近隣の集落からきていたが数カ所の屋敷を追い出されそのおりにつけ鹿児島おなご衆と土産にカルカンをもらっていた。

  なつとふみはしずこより先輩であり二年前からの付き合いなので気心は知れている中であるがふみだけは早くどこかに行けと思っている。

  部屋は六畳間に一軒の押入れそこに布団と彼女たちの持ち物が入っている。

  部屋には火鉢とみすぼらしい鏡台とちゃぶ台があるのみである。

  しょうこたちはここに4人で暮らすことになる。

  しずこは同じくおなご衆で働いていたが場所は大井川をずっと登った上流にある用山の豪農の屋敷で働いてたが、しょうこがきたタイミングで八百重屋敷に移ることになっていた。

  しょうこの挨拶がすんでしょうこの身支度をすませると用山に帰ることになっていた。

  しかしいとこのななみが増えたので主人に相談したかった。

  　しょうこはななみがなにもたべていないのか気になった。

  ななみは朝熊本で食事をしたきりだった。

  くしくも昨夜に食べようとしたフデさんのおにぎりが残っていたので渡したらななみは美味しそうに食べた、あまりにも腹が減ったので水筒の水を
  要求した、そして一挙に喉に流し込んだ。

  食べっぷりがここらにない男のような食べ方をしたななみをみてなつとふみは不思議に思った。

  まもなくして夕食と風呂の準備がはじまり５人は降りていった。

  ななみにはみなと同じ飛白の着物と同じ飛白のモンペに割烹着だった。

  　しずこは明日の夜くると主人に伝え、しょうことななみをよろしくと頼んだ。

  主人「うちは人では一人でいいんだ、明日どちらかをただしさんのところへ行ってもらうよ。

  今決めようじゃんけんしな。」

  しょうことななみはジャンケンしてななみが勝った。

  主人「じゃあななみがただしさんのところだな。」

  ななみ「ただしさんのところちかいんですか」

  主人「ちょうど田んぼをはさんだ目の前の大きな石垣の家だよ。大きなイチョウの木が何本も植えてあるよ。」

  ななみを優しく見下ろしみんなに「それじゃみんなよろしくな。」

  しょうこもななみも突然違うところで働くところが違って不安を書き立てたが近いので安心もしていた。

  くど係、ふろ係、調理係、配膳係、清掃係、子守係。２名だったがこれから3人でまわせるのでよいと思われた。

  めし、ふろ、配膳では３人でおとこ衆と主人と女主人を切り盛りする必要がある。

  田植えは６月の梅雨入りにおこなわれるがそれまでには荒手さらいなどの部落行事を行う必要がある。

  荒手さらいは近隣の農家から出方をだして共同で水田の溝の掃除をする行事である。

  この当時はそこで取れる鯉やフナなど馳走として食卓に花を揃えるので獲るたのしみも加えて若い男女の社交の場ともなる。

  このあたりの農家の作りはくど作りといって飯を炊いたりするくどが最低でも２つありこの八百重坂屋敷にはくどは３台あった、
  台所の間のと食事をする板場、さらに隠しとびらで仕切られた風呂とが隣接している。

  風呂はクドの大きいもので下から薪をくべる水は男と女でそれぞれ変えて入るのが原則だが農作業の忙しい時はそれもなおざりになることも多い。
  食事は主人とその子、おとこ衆、おなご衆と順になっており、山作業や農作業にはあとでおなご衆の握ったにぎり飯や漬物を届けるようになっている。
