* <2022-09-02 金> 2. 朝の回想

 　今朝はいつもの鶏が騒ぎ出す前に薄暗い障子越の光と共に母親の手で起こされた。
 眠いのと昨日兄たちの別れの宴で舞い上がり調子にのったのを悔いた倦怠で母
 を見起こしたがもう姉のもとにいくことは決心の絶対としていたので諦めて
 腕でまぶたを拭いた。

 　しょうこは離れで目を冷まして母屋行く障子の隙間から寝相の悪いさちおがいびきをかいて、
 ふとんを逆にして寝ていた。
 この４つ下の中学生とも今日を限り別に暮らすことになる。

　「よつお」４番目に生まれた男だから「よつお」このどうでもいい、おそらく世界でも稀にみる
 ほどの無関心の端に位置する名前、期待とかの一縷の望みもない、かといって悪魔くんのような下賤
 の侮蔑さもない、どうでもいい名前をもらったよつおは、いつしかしょうこに懐いていた、さちお
 を子分にして、ずる賢い思索をしょうこにぶつけていた。
 当初は狡賢さは名前への反発として発露していたがもはやそれは快楽に変わっていた。

 　さちおこれまで何回も兄のよつおと結託してしょうこのおかずを奪い取っていた。
 しょうは以来、飯茶碗をもつ時は、ずる賢い２羽のカラスのような兄たちから身を守るため茶碗の口縁
 を水平に保ってそこに細い目を押し付け兄たちの動きの初動見極めようと背は猫背に
 なって 攻撃に身構えていた。
 こうして身についたその癖は箸のエイリアスを懐刀に変えて、しばし、この狡猾なカラスの兄弟
 の手の甲を刺し貫いていたが多くのおかずは奪われていた。
 
 　その戦いの開幕はいつもより早めに起きた母は朝のめざめの味噌汁の匂いが近いと告げていた。
 しょうこはこのできのわるいおとこの寝相をみて、はたして今日でここをさることに後悔がもたげてきた。
 しかし決まったことに意を再度けっした。

 　寝相の悪いさちおを蹴って起こして、他の兄たちを探したが牛の餌やりや鶏の餌やりをやっているようだった。

 　しばらくして朝食が始まった。
 ご飯、味噌汁、たくあん、ツワの煮物、めっちょんの佃煮だけだった。
 長兄をふくめ三人の兄と1人の弟、母と自分５人朝食はいつもより静かだった。
 ツワは母としょうこが２、3日前に近所の山に取りにいって２時間かけて向いたものだ。
 ふたりの親指と人差し指には仲良く黒いツワの灰汁の痕がついていた。
 めっちょんは5cmほどの小さな川魚で兄の2人が先週の日曜日に50匹ほど釣ってきていたものだ。
 フデは味噌、醤油までも自家製、子供たちは当たり前のように無添加の恩恵をいただいていた。

 　しょうこのことは長兄がしきりをしていた、しずこがいるしだれもがしょうこの幸福を疑わなかった。
 ただ、さちおだけはその別れの意味を切実に惜しんでいた。
 母のフデは

 　四人の兄たちは各々仕事にでて、昼食は母とさちおと三人で食べた。
 しょうこは午後5時には溝辺を出発しなければならない不安で落ち込んでいた。

 　午後17時過ぎに長兄のとおるは職場の農協からもどってきた。
 兄として末の妹の出発を乗り換えの心配がない鹿児島駅まで送ると決めていたからだ。
 日豊本線下り吉松駅18時12始発、加治木駅19時16発、鹿児島駅着19時47分の汽車に乗る。
 
 　しょうこは長兄と二人の最寄りの日豊本線の加治木駅へと向かうことになった。
 ふたりは役場前まで歩いた、しょうこの荷物は着物と着替えなどをいれる
 と風呂敷に大つつみとなった。それをもって兄は末妹のためその未来を信じて歩いた。
 しばらくして役場前に数分遅れた加治木の路線バスが到着した。
 路線バスは溝辺-加治木の14.5kmを結んでおり溝辺住人のほとんどが肥薩線ではなく日豊本線を
 利用して鹿児島に行っていた。
 
         
 定刻通り鹿児島への汽車を確認してしょうこの土産のカルカンを買って
	 しょうこの風呂敷に入れてやった。
	 「しょうこよ。ぜったい、くじけて帰ってくるんじゃないよ、頑張ってな。」
	 しょうこは兄の言葉を心に刻んだ。
	 西鹿児島までは小一時間で着いた。
	 鹿児島本線の特急かいもん博多門司ゆきはあと３0分後だった。
	 この西鹿児島駅では大きな風呂敷を抱えた若い女は珍しい光景ではなかった。

	 しかし、しょうこは今朝母ちゃんが握ってくれたにぎりめしと高菜の漬物に水筒だけが頼りだった。
	 このひとりで福岡に何時間も客車に乗って頑張れるんだろうか、便所をなんども
	 行き来して待った。
	 にぎりめしと高菜の漬物に水筒。水筒は２番目のにいちゃんの自慢の水筒だった。
	 溝辺の水をいれているんで死ぬまで飲むなと冗談を言われていた。
	 死ぬ間際に飲むと溝辺に戻って帰ってこれるよ。
	 そうも言われていた。
