* <2022-09-02 金> 1. 鹿児島から福岡
  
  昭和31年5月  

  　九州最北の門司港から西の博多へと進み、筑後へ南に折れて、肥後へと南下したあと、
  八代を抜けて、薩摩の川内へ入り、いくつもの山裾を縫って、終点西鹿児島駅までの
  ６時間半以上かかる九州縦断の鉄の道が当時の鹿児島本線である。
  
       ??? 特急は博多、小倉、門司の停車だからC59 1のような大きな蒸気機関車は東郷に停車していないはず。
       その終点の西鹿児島駅から、上り線、筑前のほぼ北九州と博多の中間にある東郷駅に客車五両を引いたC59 1が
       黒煙を舞上げ、ホームに白い水蒸気を撒きながら入線してきた。
       汽笛がこの５月のよく透き通った青い空を震えさせた。
       
       駅の隅には花壇が整備されていてもうツツジの花の淡い朱色をチラつかせている。
       ホームの横の駅舎はガラス張りの木窓が薄く貼り付けられ中央に左右が
       入口と出口と一緒の改札の駅員がこちらを向いて小さなおかっぱ頭の少女に
       目配せをして案内をさせようとしていた。
       少女は大きな風呂敷を首に回して長い旅で顔いっぱいに煤をつけていた。
       煤のない細い目の周りだけを点滅させてあたりをおどおどと見回しながら
       かろうじてモンペのポケットから探し出した切符を駅員に手渡した。
       駅員の改札パンチのカチカチ音の小気味良い音をすぎて待合椅子のならぶ
       駅舎に入るなり「しょっこちゃんこっちこっち」と若い女の声がした。
       そこには妹を福岡まで呼びよせた姉のしずこが待っていた。
       「がんばったね、よくきたね」しずこは妹の荷物をやさしく抱いてうけとった。
       姉は待合椅子に妹を座らせ手拭いで本人も気づいていない顔いっぱいの煤を拭いてやった。 
       
       東郷駅のある宗像は黒田藩御用金鉱が全盛期だったため町には活気があった。
       というよりは金鉱は隠蔽され地元住民もしらないものが多かった。
       むしろ庶民には炭鉱が大井と池野に二つあったことによるものが大きかった。
       太平洋戦争も戦況の不利が見え始め内需拡大政策から炭鉱開発への補助金
       目当てに大井炭鉱も開発され宇部興産の資本と人員が入り込んでいた。
       その炭坑夫の落とす金を目的に居酒屋やカフェーの類もちらほら見受けられ
       町では流行りの映画館も数件あった。
       二人がいる駅の北側は緩い下り道となっていてその先まで商店がならんでいた。
       
       二人はバスの時間を確かめた後待ち時間の間にうどんを啜ることにした。
       駅舎のうどん屋は立ち食いだったが北九州では評判のよい東筑軒がやっていた。
       姉はかしわうどんを二つたのんで置いてあるやかんから湯呑みにお茶をついだ。
       「よくきたね、つかれたやろう」
       妹のしょうこは気丈に答えた
       「そうでもなかったけど博多駅の乗り換えで迷った」
       しばらくしてうどんが目の前にでてきた。
       しずこは「こしゅ(とうがらし)をこっちじゃ'こしょう'って言うんよ」と
       いいながら一振り妹のうどんにかけてやった。
       しょうこはかしわの匂いに少しけげんさを抱いたがこれが美味しいんだと
       改めて異郷にきたことをかき消すようにをうどんをすくった。
       横にいる姉と何ヶ月ぶりかに一緒に食べることことがうどんをすくうたびに
       嬉しさにかわっていった。
       そして不安の胃に流し込むうどんにみたされて、
       うまれてはじめて一人で乗った汽車の出来事を振り返った。
