* <2022-05-16 Mon> 文次郎とななみ
  杉の丸太を大井川の流れに逆らって縦に組み湿らした蔓を叩いてそれを回して吊り上げ、
  その横に細い枝を敷き詰め上に杉の葉と赤土をこねた粘土で塞ぐ簡易な構造の桝丸橋がある。
  掛けた櫓は都合４本岸の２本と中の２本それが杉の丸太の重みと赤土でなんとか持つだろうという近くの一杯飲みの土建屋の指示
  で掛けたのだ、土建屋は重けりゃ重いほど強いと威張り散らしていた。
  自動車も通ることができるが揺れは響いていつかは破壊されてしまうほど不安な橋だ。
  案の定次の年の台風でこの橋はなくなった。
  大井川は護岸の整備がほとんどされておらず川に寄り添って上流につづく道路の横には朽ちて
  ところどころに折れたり穴がほげている桜の並木が奥へと点在していた。
  この時だけは綺麗に大井川に落ちた桜の花びらは先日の雨の日の川の流れが多数を下流へとながし
    茅や植物の隙間に残骸を残しているだけだった。
    橋には欄干に軋む音と詰めた赤土が水面へと落ちる音がしていた。
    左手にはよく開墾の跡が見える田畑が低山の懐に入る様相を示していた。
    その橋を渡ってすぐに三叉路があってその突き当たりに畑がひろがっていた。
    一人の細みの男がその三叉路を右に折れかかっていた。
    畑には数人の若い娘が絹サヤを採取していた。
    一番近くの黄色い農作業帽子をしめた娘に男の中音の橋に笑い声が輝くようなよく通る声で話しかけた。
    「おじょうさん、生が出るね」
    ななみは、喉の奥にやさしい輝く笑い声がすうっと流れてきて、声の主を見上げた。
    「こんにちは。じゃっど！」
    男はカーキ色のズボンに脚絆を巻いた半長靴に同じくカーキ色のジャケットを着ていた。
    この復員姿の男は笑い声を増して鹿児島から来たのかと尋ねた。
    ななみはじゃっどをつけると鹿児島出身と思われると思っていたのでしめたとしたり顔で、
    じゃっどと答えた。
    太平洋戦争の末期になると海運を生命線としている日本の運送船の重要度は増して、その分
    潜水艦による魚雷や空爆などの攻撃は容赦無く、多くの輸送船が北、西、南太平洋の海の藻屑と化していた。
    そんな深刻な状況の中、
    文次郎も運送船に乗っていた。
    そしてまさに帰還できたということは奇跡に等しかった。
    文次郎は月の復員した日、つまり老いた母にふたたび会えた日に、平家由来の宗像に伝わるひらとも様に参ることを月課としていた。
    平和(ひらとも)さまと和宗(ともむね)さまは大井に残る平家落武者伝説を謂れとしている。
    平家が壇ノ浦の合戦に破れ一門の平和(ひらとも)様と知宗(ともむね)様もこの宗像の里まで落ち延びてきた。
    幾日か詫びしい里山の奥の暮らしをしていたがある時源氏の追手が現れた。
    用山と大井の低山の境に逃がれた平和(ひらとも)様は眼下に源氏の白旗が田畑になびくをみて「今日限りの命ぞ」と観念して潔く自害された。
    同じく知宗(ともむね)様は大井と田島の境で自害された。
    里の人々はこの二人の武将を菩提をともらってそれぞれに石祠を建てて祀っている。
    武将を冠しているため出征の折には参る者も多く、薪を集める目的もあって山道はよく整備されていた。
    文次郎もその習わしにしたがって出征の前日にひらとも様に登っていた.
    じゃっど。その響にはかつて死んでいった同胞を思い起こし、ただうなずける、その
    娘の可愛さに、自分の境遇と自分の今していることのなんの射線もないので、
    文次郎はななみに、一緒にひらとも様にのぼるかと言った。
    ななみは文次郎の人格に慈しみに近い安心感のような懐かしみのようなものを感じた。
    だからその文次郎の正当な理由のひらとも様に一緒に登ると言った。
    ななみは部屋に駆け戻って急いで支度をすませて戻ってきた、手にはここではカメラで通っている携帯を油紙に包んでもってきた。
    文次郎はやさしく背中を推して名もなき低山の登口への道へ二人は入って行った。
    薪とりでゆるいよく整備された山肌は登りやすかった。
    ひらとも様までほんの１０分も登ったところで着いてしまった、小さな石造りの祠が二つ横に並んでその中には福神売りが
    押し付けて邪魔になった紙粘土の恵比寿様やらが沢山置いてあった、どれがひらとも様なのかわからないななみは文次郎に尋ねたが
    文次郎も知らなかった。
    私のかあちゃんもしらんやろうなとも言った。
    ななみは文次郎の合唱が終わるのを見計らって持ってきた油紙に大事に包んだ携帯を福神の恵比寿様で隠すようにおいた。
    携帯のバッテリーの残量は10%を切っていたがいつかなんかの役に立つのではと思っていた。
    文次郎は山を下りながら母は若い時事故で失明し片目がないと伝えた、本村橋の永井さんの母と仲が良く毎日遊びに行っている
    でもそこの二人の兄弟にはどうも嫌われているようだとも言った、例の乞食兄弟のことだ。
    特に弟にはほうきを逆さに置いて早く帰れといじめられているらしい。
    そういうと文次郎の笑い声が木々の間の空に舞い上がった。
    これはカツオのことだ。
    そう思った時出太鼓の音が三度ひびいて、1日の作業の終わりを告げていた。

