* <2022-09-02 金> 1. 鹿児島から福岡
  
  　昭和30年5月。午前6時50分。  
  鹿児島駅、前夜始発20時30分門司港行き普通快速の蒸気音が村山田の白水峠の山を超えて聞こえてきた。

  　鹿児島本線上りの難所である白水峠を半円を描くように避けて下り坂に現れたC591は地響きとともに、
  安堵の白煙を無風の空に舞わせて、水蒸気の渦をホームになだれこませ、
  その車輪の悲鳴は峠から別れた国道３号線までの谷に轟かせて、入線してきた。

  　そして汽笛は、この５月のよく透き通った青い空を震えさせた。

  　この年C591は九州で運行を開始した機関車で優美な姿は貴公子と呼ばれていた。
  無停車運転は150kmを超えて、牽引能力はそれまでの400トンから500トンに増強された。
  昭和36年から37年の電化に伴う引退の後、九州の準鉄道記念物に選ばれ、半世紀を経て、
  北九州鉄道記念館(門司港レトロ地区)に展示されている。

  　東郷駅の構内は花壇がよく整備されていてもうツツジの花の淡い赤紫色をチラつかせている。
  機関車は現在も残る宗像大社の白い宣伝柱を横にみて、ぴたりと停車し、同時に連結機のつまづき合う連鎖音を響かせた。
  しばらくして手動の乗降扉を開けて、眩しい空を手で遮りながら客たちが降りてきた。

  　一番ホームの横に建てられた駅舎はガラス張りの木窓が薄く貼り付けられた中央上の壁面とその下に左右が
  入口と出口と一緒の改札の中の駅員がこちらを向いて小さな女に目配せをして案内をさせようとしていた。

  　女は大きな風呂敷を首に回し、10時間の長い汽車の旅で顔いっぱいに煤をつけていた。
  煤のない細い目の周りだけを点滅させてあたりをおどおどと見回しながら
  やっとのことでいっちょうらのワンピースのポケットから探し出した切符を駅員に手渡した。
  このワンピースの柄は前面が煤で汚れてしまってわからなかったが、
  座っていたためはっきりと背中と尻だけが白地の花柄だとわかった。

  　駅員の小気味良い改札パンチのカチカチ音をすぎて待合椅子のならぶ
  駅舎に入るなり「しょっこちゃんこっちこっち」と若い女の声がした。
  そこには妹を福岡まで呼びよせた3つ年上の姉のしずこが待っていた。
  「がんばったね、よくきたね」しずこは妹の背負った風呂敷包をやさしく抱いてうけとった。
  姉は待合椅子に妹を座らせ手拭いで本人も気づいていない顔いっぱいの煤を拭いてやった。 
       
  　東郷駅のある宗像は黒田藩御用達の金鉱で栄えた歴史をもつが当時の庶民の生活に影響を
  与えたのは大井と池野に炭鉱が二つあったことによるものが大きい。
  太平洋戦争の戦況の不利が見え始めたころ、内需拡大政策から炭鉱開発への補助金
  目当てに大井と池野の炭鉱も開発され宇部興産の資本と人員が入り込んでいた。
  その炭坑夫の落とす金を目的に居酒屋やカフェーの類もちらほら見受けられ
  町では流行りの映画館も数件あり栄えていた。

  　当時、鉄道で鹿児島から福岡にいくには３種の汽車があった。
  一つ目は夜行列車急行さつま東京行き、鹿児島始発23時30分、博多到着7時07分。
  二つ目が同じく夜行列車急行霧島東京行き、鹿児島始発20時30分、博多到着5時09分である。
  そして三つ目が普通快速門司港行きである。
  当時は急行しかなく乗り継ぎ時間を考えると各停しかとまらない東郷駅などに向かう
  には急行券不要の普通快速はコスパにもすぐれ、上福を志す若者に人気があったのだろう。

  　いっぽうの特急の運行は1958年まで遅れた、有名な特急はやぶさ東京行きは鹿児島博多間を6時間半に大幅に短縮した。
  しょうこは里帰りなどで帰郷する場合は特急はやぶさを利用することになるが
  私が母から聞いていた6時間半かかったという話は、普通快速の10時間の記憶をいつしか塗り替えた
  のだろうと推測する。

  　二人がいる駅の北側は緩い下り道となっていてその先まで商店がならんでいたが、
  南側は、標高わずか271mの許斐山を遠方に眺め、ちらほら農家が散らばる未開の山裾だった。

  　二人はバスの時間を確かめた後、待ち時間の間にうどんを啜ることにした。
  駅舎のうどん屋は立ち食いだったが北九州では評判のよい東筑軒がやっていた。
  姉はかしわうどんを二つたのんで置いてあるやかんから湯呑みにお茶をついだ。
  「よくきたね、つかれたやろう。」
  妹のしょうこは気丈に答えた。
  「乗り換えがなかったのでそうでもなかったけど、最初は不安だった。」
  しばらくしてうどんが目の前にでてきた。
  しずこは「こしゅ(とうがらし)をこっちじゃ'こしょう'って言うんよ」と
  いいながら一振り妹のうどんにかけてやった。
  しょうこはかしわの匂いに少しけげんさを抱いたがこれが美味しいんだと
  改めて異郷にきたことをかき消すようにをうどんをすくった。
  横にいる姉と何ヶ月ぶりかに一緒に食べることが、うどんをすくうたびに
  嬉しさにかわっていった。
  そして不安の胃に流し込むうどんにみたされて、
  うまれてはじめて一人で乗った汽車の出来事を振り返った。


  　https://www.youtube.com/watch?v=h6Ol3eprKiw





