* <2021-06-20 Sun> 2013に高菜漬けをしらべたテキスト発見した。
* 20120316 

高菜の塩漬け（２０１２年３月１５日開始）

１、高菜は切り取ってすぐに干す、干す時間は丸一日目安。
　　人によっては切りとってそのまま畑で干す人もいる。
　　ただし、雨には要注意です。
　　干す前に、大きいものは４分の１、普通以下は２分１に株から縦に
　　切り分けておく。
＃　　白菜の場合なら、切り取ってすぐに４分の１に切ってを水洗いしてから
＃　　丸一日干す。
　　高菜の大きさは３、４０cmのものがベストらしい、よんぱちなどの肥
　　により、固くなったりするらしい。
　　育て方はまた別途綴る。

２．これをよく振って泥や砂を取り除く。
　　
３．最初の塩揉みを行う。

　　高菜を横にして両手で握られるほど選んで、それに塩を振る。
　　塩は、一差し指、中指、薬指、小指の４本で軽く掴む程度。
　　もみ加減としては、絞って汁が落ちてくる程度までもむ。

４．これを樽に漬け込む

　　樽は、高菜の量によって決めるが、良く荒って、沸騰した湯を
　　まわしかけて消毒してもよい。
　　これに隙間がなくなるようにきっちりとつけ込んでいく。　
　　一段できたら、塩（例の４本指でつかんだ感じを）まんべんなく
　　振っていく。これを２度するようだ。
＃　　この際に近所の奥さんはニンニク（半分にきっているのか）をいれているらしい。
　　また、揉んだ時の塩が甘いと高菜がピーンと立ってくる場合もあるらしいので
　　重石の重さなど研究余地はある。
　　以後、同じく、隙間無く、高菜の量だけ段を重ねて行く。
　　桶に合った丸板を置き、重石（１２kgを２つ程）はきれいに洗ったものを使う。

5．これを２日から３日置いておくと塩が上がってくる。
　　この汁気は灰汁を含んでいるので一端、ざるに上げて汁気を切る。

　　この歳、一株ごと丁寧にとって水気を切っていも良いが気分で適当でもよいらしい。
　　ざるに上げてからは２時間程が目安である。

６．最後（２回目）のつけ込み。

　　さっきの樽を洗って使う。
　　とにかく隙間ができると虫の原因になるので隙間ができないように
　　注意して、１段目を作る。
　　最初のつけ込みと同様に塩だが最初より２回目を多くする。
　　最初と違うのは虫がつかないように胡椒（赤唐辛子を５mm位に切ったもので
　　たね込み）を５本（詳しく量はわからず）分位。１段毎に振っていく。
　　付け方は、最初と同じようにする。

　　１月なるかならないほどで青色から茶色へ変化する。
　　その間、汁が多くでていると酸っぱくなるのでタオルなどを使いとる。

７．最後のつけ込みから２日、3日で食べられるようになる。

  塩だしは、水は替えをやりながら、半日程水につけて行う。

　　塩の量にもよるが半年まで食べられる。

＃　　高菜は１月近くで熟成するのでその時々で味も変わるだろうが、夏は、
＃　　みそでも何でも開けられないらしい。

　　あの美味なる高菜のごま油傷めもこの夏をこさないとうまくならないだろう。

* <2021-08-03 Tue>
 + 力丸清一さんに電話
   + S27生まれ(1952)
   + 詳しく調べてみないとわからん
   + 女子衆三人
   + 小学校5/6年にうちが建て替わった。
     1952,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,67
     0   ,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16
   + 今とは母家といなやが逆の位置
   + 味噌小屋,漬物小屋とわかれていた。
   + こえたんごかつぎはむつこさんが一人でやっていた。
 + かあちゃんの年齢をもう一度確認
   昭和 9	1934	87	戌
   昭和 10	1935	86	亥
   昭和 11	1936	85	子
   昭和 12	1937	84	丑 0  1
   昭和 13	1938	83	寅 1  2
   昭和 14	1939	82	卯 2  3
   昭和 15	1940	81	辰 3  4 
   昭和 16	1941	80	巳 4  5
   昭和 17	1942	79	午 5  6
   昭和 18	1943	78	未 6  7
   昭和 19	1944	77	申 7  8
   昭和 20	1945	76	酉 8  9
   昭和 21	1946	75	戌 9  10
   昭和 22	1947	74	亥 10 11 
   昭和 23	1948	73	子 11 12
   昭和 24	1949	72	丑 12 13 たえこ
   昭和 25	1950	71	寅 13 14
   昭和 26	1951	70	卯 14 15 清和誕生
   昭和 27	1952	69	辰 15 16
   昭和 28	1953	68	巳 16 17
   昭和 29	1954	67	午 17 18 
   昭和 30	1955	66	未 18 19 上福　やおじゅうさん(しずこから)(30/11ともやす誕生)
   昭和 31	1956	65	申 19 20
   昭和 32	1957	64	酉 20 21
   昭和 33	1958	63	戌 21 22
   昭和 34	1959	62	亥 22 23
   昭和 35	1960	61	子 23 24 結婚
   昭和 36	1961	60	丑 24 25
   昭和 37	1962	59	寅 25 26 力丸家建て替え
   昭和 38	1963	58	卯 26
   昭和 39	1964	57	辰 27
     
* <2021-08-13 Fri>
 + 清和
   + 写真２枚
     + 力丸家の玄関の坂(みずえ,初枝)
     + むつこさんたちと旅行
* <2021-08-16 Mon>
  + 吉田直人さん
    人の名前をわかる範囲で記述
* <2021-09-11 Sat>
  + しずこおばちゃんと話す
    + やおじゅうさん
    + しょうこは二十歳じゃない18才で上福していると判明
    + 力丸家に直接奉公した
    + いずみさん
    + 用山にもいたが覚えていない。
* <2021-09-12 Sun>
 + 清和電話する
   + たえこ
   + ともやす30/11
   + 来年田んぼの苗してやる
     
* <2021-09-12 Sun>
 + ちえみ宗像来る
* <2022-03-16 Thu>
  + 文次郎の長女
    太郎とリードで散歩して梅の木に登らせていると家の前に不審なグレーの軽自動車が止まって
    なにやらやっている。
    電話でもしているのだろうと太郎を家にいれて木の剪定をしていたら後ろから声をかけられた。
    「この家の自転車にいつも乗っているおじさんはどうしていますか」
    近所の人がよく散歩で親父にあって、その後見ないのでよく尋ねてくる類だなと思った私は
    「去年11/8に亡くなりました」と色々と説明していると私のばあさんの新の話がでた。
    「ここのおばあちゃんが死んだ後すぐに私のばあちゃんも死んだんです」
    聴くと片目のばあさんのことだった。
    そしていろいろ話をしていると文次郎は海軍にいっていたので決まった戦地はないとのこと。
    これでななみと文次郎との関わりを想像する大きな手がかりが見えた。
    それにしても太郎との散歩もただの思いつき、不思議な偶然が呼び寄せた出会いだった。
* <2022-04-22 Fri>
  + ばあさんが18才で上福した時溝辺から加治木には南国バスを利用し55号線を下ったとの考察が濃厚になった
  + 加治木駅の現在の駅舎は小学校の時にばあちゃんの実家に里帰りに着いて行った時このような
    駅舎に夕方着いた記憶がかすかにあるような他の記憶からすり替えたような曖昧な映像が浮かんだ。
    だから前述のバスによる工程が濃厚との判断がより正しいと思わせる。
  + 加治木駅は1945年4月26日 - 加治木空襲により初代駅本屋焼失。
    とある、ばあさんから以前に聞いていた小学校校庭に爆弾が落ちていたとの話を思い出した。
    これは加治木空襲の際にダグラスA-20が沖縄から18機の編隊を組んで爆撃したその一部の機が溝辺の小学校
    に落としたのではないかと推測したがダグラスA-20の航続距離からマリアナ諸島のサイパンなどから
    はB-29の航続距離5000kmオーバーを持ってしか不可能だから沖縄から飛び立ったと想定したまでにとどまった。
    
* <2022-04-22 Fri>
  + 太平洋戦争と海上輸送
    太平洋戦争は、開戦に至るまでの経緯はともかく、直接的な動機は米英を中心とする連合国のわが国に対する経済封鎖、なかでもその殆どを米国に依存していた石油が、米国の　「対日石油全面禁輸」　によって確保出来なくなったことが、わが国が開戦に踏み切った最大の要因であった。
    したがって、資源のないわが国が開戦にあたってとった基本方針は、南方の資源地帯を占領し、そこから戦争遂行と国民生活に必要な石油、鉄鋼、非鉄金属、ゴム、ボーキサイトなどを確保するというものであった。
    開戦と同時に日本軍は、真珠湾の奇襲攻撃と同時に南方地域に進出その戦域は、西南太平洋全域におよび北はアリューシャン、東はミッドウェー、南はフィジー諸島を結んだ広大なものとなっていった。
    そして、この戦いを左右するカギは、いつにかかって海上輸送の確保にあった。その意味から太平洋戦争は、世界戦史に例を見ない大海洋作戦であった。
    しかし、その結果は、わが国商船隊の壊滅とともに日本の生命線は絶たれ、敗戦を迎えた。

    １ 開戦にあたってわが国の商船は総べて　「戦時海運管理令」　によって、一元的に管理された。
    ２ 保有船腹を軍の作戦行動と民需輸送にどう配分するかは、開戦に踏み切る前の重要課題であった。
       現有船腹でも、果たして海洋作戦が主力となるこの戦争に対処できるのかと言う不安があった中で、船舶を作戦と民需にどう振り分けるかは国家としての判断が問われた。結局、軍の強い発言力でそれぞれ２分の1　(300万トン)　ずつの配分となった。　ただし、緒戦が完了すれば、軍の徴用船の一部を民需に回すことで合意ができた。
    ３ 開戦後の船舶の被害は、緒戦の優勢であった一時期こそ僅かであったが、昭和17年6月、ミッドウェー海戦で米軍　(連合軍)　に敗北し、制空権、制海権を奪われ後退に転じてからは、敵の潜水艦や航空機の攻撃による喪失は予想をはるかに上回るものとなっていった。
       開戦に踏み切るかどうかを判断する政府首脳会議で、敵の攻撃による船舶の被害をどの程度に見るかが重要な議論となった。
       その時海軍が提出した船舶の喪失は、約年60万トンであった。これは確たる根拠のない、辻つま合せのもので、一説には第1次世界大戦の英国商船の被害を参考にしたものであったと言われている。次の表は、各年度毎の喪失量を示したものである。
      各年度の船舶喪失量 （機帆船、漁船は除く ）
    | 年度       | 隻数        | 船腹量         |
    | 昭和１６年 | ９隻        | ５万総トン     |
    | 昭和１７年 | ２０４隻    | ８９万総トン   |
    | 昭和１８年 | ４２６隻    | １６７万総トン |
    | 昭和１９年 | １,００９隻 | ３６９万総トン |
    | 昭和２０年 | ７４６隻    | １７２万総トン |
    | 合計       | ２,３９４隻 | ８０２万総トン |
    ４ ここに至って初めて軍は、海上輸送の重大さを認識し、海軍は輸送船護衛強化策として昭和18年11月　「海上護衛司令部」　を設け、海防艦の緊急建造に乗り出した。
       また、陸軍は宇品の暁部隊で徴用船護衛のため、船舶砲兵隊の強化に乗り出した。しかし、これ等の諸対策は既に手遅れで、輸送船の喪失を食い止めることは出来なかった。
    ５ 喪失商船の補充として、陸海軍ともに小型の機帆船の徴用や大量建造を行い、漁船も輸送のために徴用した。これ等の船舶も商船同様その殆どが壊滅した。
    ６ 漁船については、開戦と同時に洋上監視を目的として　「特設艦視艇」　として400隻をこえる船が海軍によって徴用された。
       昭和17年4月18日、米空母からドーリットル指揮によるB25中型爆撃機の東京初空襲をいち早く通報したのは、徴用漁船第23日東丸であった。この船は、海軍司令部に6通の敵情報を送った後、30分後に敵機により撃沈され全員が戦死した。
    ７ 商船について沈没原因を数字で見ると、第1が潜水艦の魚雷攻撃によるもので、1,153隻これは総トン数で約60％、第2が空爆によるもので902隻、次に触雷が250隻、砲撃その他が89隻となっており、わが国の海上輸送は潜水艦の雷撃により破壊され、空爆によって止めを刺されたとも言える。

* <2022-04-26 Tue>
  + 文次郎とななみ
    コンクリートで建造されてまもない桝丸橋を渡ってすぐに三叉があってその突き当たりに畑がひろがっていた。
    一人の細みの男がその三叉路を右に折れかかっていた。
    畑には数人の若い娘が枝豆を採取していた。
    その一人に男が中音のよく通る声で話しかけた。
    「おじょうさん、生が出るね」
    ななみは、喉の奥に笑い声が輝いているような優しい声に、はっとして声の主を見上げた。
    「こんにちは。じゃっど。」
    男はカーキ色のズボンに脚絆を巻いた半長靴に同じくカーキ色のジャケットを着ていた。
    この復員姿の男は笑い声を増して鹿児島から来たのかと尋ねた。
    ななみはじゃっどをつけると鹿児島出身と思われると思っていたのでしめたとしたり顔で、
    そうだと答えた。
    太平洋戦争末期になると海運を生命線としている日本の運送船の重要度は増して、その分
    潜水艦による魚雷や空爆などの攻撃は容赦無く、多くの輸送船が北、西、南太平洋の海の藻屑と化していた。
    そんな深刻な状況の中、文次郎も運送船に乗っていた。
    そしてまさに帰還できたということは奇跡に等しかった。
    文次郎は月の復員した日、つまり老いた母にふたたび会えた日に、平家由来の宗像に伝わるひらとも様に参ることを月課としていた。
    ひらとも様とは宗像の小高い数十メートルの山の頂きに設けられた石作りの社で平家由来とされるが
    その真偽は定かではなくよく地方に点在する言い伝えの類だった。
    武将を冠しているため出征の折には参る者も多く薪を集める目的もあって山道はよく整備されていた。
    文次郎もその習わしにしたがって出征の前日にひらとも様に登っていた。
* <2022-04-27 Wed>
  + コンクリート制の桝丸橋の建造は昭和47年だった
* <2022-05-08 Sun>
  + 文次郎とななみ
    杉の丸太を大井川の流れに逆らって縦に組みその横に細い枝を敷き詰め上に杉の葉と赤土をこねた粘土で塞ぐ簡易な構造の桝丸橋がある。
    自動車も通ことができるが揺れは響いていつかは破壊されてしまうほど不安な橋だ。
    大井川は護岸がほとんどされておらず大井川に寄り添って上流につづく道路の横には朽ちて
    ところどころ折れたり穴がほげている桜が奥へと点在していた。
    この時は綺麗に大井川に落ちた桜の花びらは先日の雨の日の川の流れが多数を下流へとながし
    茅や植物の隙間に残骸を残しているだけだった。
    橋には欄干させなく軋む音と詰めた赤土が水面へと落ちる音がしていた。
    その橋を渡ってすぐに三叉があってその突き当たりに畑がひろがっていた。
    一人の細みの男がその三叉路を右に折れかかっていた。
    畑には数人の若い娘が枝豆を採取していた。
    その一人に男が中音のよく通る声で話しかけた。
    「おじょうさん、生が出るね」
    ななみは、喉の奥に笑い声が輝いているような優しい声に、はっとして声の主を見上げた。
    「こんにちは。じゃっど。」
    男はカーキ色のズボンに脚絆を巻いた半長靴に同じくカーキ色のジャケットを着ていた。
    この復員姿の男は笑い声を増して鹿児島から来たのかと尋ねた。
    ななみはじゃっどをつけると鹿児島出身と思われると思っていたのでしめたとしたり顔で、
    そうだと答えた。
    太平洋戦争末期になると海運を生命線としている日本の運送船の重要度は増して、その分
    潜水艦による魚雷や空爆などの攻撃は容赦無く、多くの輸送船が北、西、南太平洋の海の藻屑と化していた。
    そんな深刻な状況の中、文次郎も運送船に乗っていた。
    そしてまさに帰還できたということは奇跡に等しかった。
    文次郎は月の復員した日、つまり老いた母にふたたび会えた日に、平家由来の宗像に伝わるひらとも様に参ることを月課としていた。
    ひらとも様とは宗像の小高い数十メートルの山の頂きに設けられた石作りの社で平家由来とされるが
    その真偽は定かではなくよく地方に点在する言い伝えの類だった。
    武将を冠しているため出征の折には参る者も多く薪を集める目的もあって山道はよく整備されていた。
    文次郎もその習わしにしたがって出征の前日にひらとも様に登っていた。

* <2022-06-09 Thu>
  + ばあさんの梅干し
    + 2021年は5/24に3升,一晩アク抜き,450gの塩で梅酢作った
      この塩の算出の元になったのが2019/8/7 にばあさん本人から聞いたことをスマホのメモにしていた
      以下の内容からだったと忘れていたがそうだと思う。
      + memo の中
        6月,梅採取,一晩水につけてアク抜き,一升,８寸
      + 一升,８寸はばあさんが繰り返し言ってた言葉、それをもとに調べて１升150gの塩と算出したっぽい
      + だから３升450gだ、８寸は180の80%的意味合いだったか。
      + 実際これで去年梅酢漬けが成功している
    + 実はこの塩分濃度一般(長谷川さんの奥さんにも聞いたら)
      梅1kg->塩180g->焼酎25ccとメモをもらったので一般は梅の18%にするということなのでぴったし。
    + ところがばあさんの梅干しは一般が一升換算324gのところ150gと半分以下の塩分濃度なんだ
    + じいさんはおれの作った梅干しはばあさんのうめぼしじゃないといって死んでいった
  + ばあさんの梅干し塩判明
    + 一升,８寸は、立法寸のことで8/64.8272=0.123405となる
    + 1800*0.123405=222.129が一升あたりの塩の重さとなる
* <2022-06-17 Fri>
  + 中村家のばあさんは田植え後カエルがうるさいと警察にでんわしてカエルはあんたより
    昔からいるもんだからどうしようもないんだよ。
    とかいわれたらしい。
* <2022-07-01 Fri>
  + 深田図書館
    + 宗像むかしの生活研究1むかしの子どもの学校生活と遊び
      + 昭和7年弁当箱はアルミニウムおかずは梅干しらっきょう漬物が主体、時にかまぼこや天ぷら
      + 女の子の遊びに手毬つきがあるので７才のたえこといっしょにしょうこが寝ている清和背負って遊んでいる
      + 1960年代からの高度成長による変化
      + おかしとして家になったくだものが主だったが、はったい粉(麦を炒って石臼でひいたもの)
      + 妊婦は腹がせきだすまで、つくまみこむまで働き続けた、仕事中少々腹がせいてもおさまるまって仕事を続けた
      + ぎゅうたらしゅう(仰山)に言うのをはずかしがった
      + たいてい村にはひとりかふたりの産婆さんがいた
      + 妊娠６ヶ月ころにしりもちをついたら姑さんが「そりゃでるばい、はよう黒砂糖馬たべときない」といわれたくさん
        食べた、流産せんおまじない
      + あんたがたどこさ　肥後さ、肥後どこさ　熊本さ、熊本どこさ　えんばさ、えんばどこゆきや　たぬきがおってさ、
        それを漁師が　鉄砲で打ってさ、煮てさ　焼いてさ　食ってさ、うまさのさっさ
        と叫んでまだ茅葺の母家の屋根にシュートを放った、それがバスケットの見事なシュートだったのであぜんとしたたえこ
        は泣き出すのを堪えようとしていた。
        それを縁側から見ていた姑の笑い声がみんなを振り向かせて笑わせた。
        たえこだけが笑わなかった。
      + おきうと、おきうと草を水にさらして、ごみをとり、干し、湯にもどして炊き、煮溶かして、最後に酢を少量いれて、火おとめて
        よくねり型にながして硬め、胡麻醤油でたべる。

* <2022-08-28 Sun>
  + 千恵美さんからlineで静子おばちゃんが朝2:00夏バテかなで運んだが心臓が
    悪くてそのまま亡くなったとの連絡。
  + 昨晩名古屋のおじさんのところへ静子おばちゃんが知らせにきて、じいちゃん一人
    になったなあといったそうです。
    合わせて昌子は?とも恵子さんが昌子さんは亡くなったでしょう。と答えたらしい。
  + 私には静子おばちゃんといつも一緒にいる昌子がいないのでしょうこは?といったと
    思った。
  + この度は静子叔母様のご冥福を心よりお祈りいたします。
    和幸様、みどり様、健二様、ご家族様のご心労ご察しいたします。
    通夜、告別式などお忙しいことと思いますので一筆にて失礼します。
    
    昨年偶然に静子叔母様と電話で話を伺えたのがほんとうによかった。

    母の位牌を持って鹿児島参りをしたいと思いながら、もう一度お話をしたいと
    思っていましたが、ついに果たせませんでした。
    母昌子と静子叔母様が福岡の宗像市で働いていた頃を何かしら記憶
    に残そうとしているので残念ですが、何か形にはしたいと思います。

    皆様、くれぐれも心落としないよう御体をご自愛ください。

    永井 利一
