* <2022-09-02 金> 3. 朝の回想(セーラー服の少女)

	 鹿児島本線特急はやぶさ博多・門司港ゆきの定刻になった。
	 汽笛が構内に響いた。
	 三等の切符は機関車のすぐ後ろだったが一番後尾の待合にいたので
	 車掌に前に行けと促され重い荷物を振りながら機関車の後ろの客車
	 に乗り込んだ。
	 席をさがすとさすがに始点だから空いている。自由席にして正解だった。
	 あんどで一番ひろいだろう対面席に荷物を置いて進行方向に向かって
	 座った。安心したこれでねーちゃんのところに行ける。
	 あとはお昼にかあちゃんの握り飯食ってにいちゃんの水飲めばいいだけだ。
	 先頭の機関車の轟音は客車の椅子や床まで震え上がらせる。
	 安堵は恐怖と家族の希望が合いまみれ朝早く起こされた眠気をかき消して
	 窓に肘をついて気取りなんかをよそう。

	 ふと目を車内にうつすと４列向かい席の対にひとりのセーラー服の少女が
	 いる。少女はもしかしたら同じくらいの年かもしれない。
	 その目は驚きに開いてどこを見ているかわからない。
	 気でも違うのかとおもうが身なりは整然と気品さえもっている。
       
	 私は今家族との別れと自分の将来への旅立ちにいるので人のことに関わり合う
	 立場にない。そう思ってしばらくすると眠りに着いた。

	 客車には機関車のたちこめる煙でいっぱいになっているのでそれで起こされた
	 と思ったが、さきの少女が肩を叩いていた。
	 「この指輪はあなたのものではないですか」
	 みると翡翠のような青緑の石がついている銀色の指輪だった。
	 それが欲しいと思ったが、違うというと、あなたの席にあったという。
	 どういうことかと尋ねると。
	 さっき空席だった時に拾ったら次の瞬間あなたがそこにいたという。
	 「あんたあたまがおかしいんじゃないの」
	 さき程の綺麗なセーラー服は煤けて顔も煤けてなぜかこれ以上とがめる気がしない。
	 「ここに座って」というと
	 「いいよ」といって座った。
	 しょうこは今朝母に起こされてまだ眠たいまま眠っていたからまだ夢の中にいる。
	 だがここで正義を尽くさねば兄たちが怒る。
	 しかたないこれに付き合って夢見るよ。
	 「あんたなまえは」「ななみ」「あたししょうこ」
	 「どこから」「くまもと」「あたしかごしま」
	 機関車の先頭客席は煙を舞い込んで石炭の匂いが立ち込め眠りを誘い込んだ。
	 めざめたしょうこは前の席に眠るさきの少女をみた。
	 動かなくなった汽車は駅について「日吉」のアナウンスを響かせていた。
	 そしてまた眠りについた。
	 しょうこは「筑前新宮」のアナウンスが響いて起こされた。
	 目の前にはまだ少女がいた。
	 少女の肩を揺らして、「どこまでいくの」と叫んだ。
	 少女は女の顔みて笑った。
	 「あんたもおんなじもんよ、東郷で降りるけど」
	 少女は人差し指にある指輪を目の前に出して
	 「この指輪はなん」「しらん」
	 「この機関車はもしかしたらC591」「しらん」
	 「わたしも降りる」「なんで」
       東郷駅に汽車が着いた頃しょうこは降りて改札をさがしていた。
       このセーラー服の少女はどこかへ消えてしまっていた。
