* <2021-02-28 Sun> 8. 景色の中の乞食兄弟

  　しずことしょうことななみ、2人のおなご衆は11時の出太鼓で戻ってくる主人やおとこ集やなどに出す昼食の
  準備のため、一階の台所にきていた。

  昼の準備は握り飯と味噌汁と漬物とお茶だけだったのですぐに終わってななみ以外は２階に戻った。
  
  　ななみは八百重屋敷の玄関道を出て大井の田園とその向こうにある茅葺屋根が連なる部落や川の上流を眺めた。

  　八百重屋敷から小さな大井川を上流に桜並木を辿ると４つ橋がかかって一番奥の端から小型のダンプが黒煙を上げて川に沿った道を下って八百重屋敷橋から道路に出ては東郷駅の方に向かってはまた遠くの橋を渡るということを繰り返していた。

  　ダンプには黒い石のようなものつまり石炭が積まれていた。

  　そのダンプのため古い桜の枝葉は拒んで切られて通るのを助けていた。

  道は穴ぼこだらけでいたるところに雨水をためてはタイヤでひかれ乾いて補修の不揃いの砂利が埋められていた。

  その補修が愛ではなく諦めのものだった。

  　ダンプはワダチを二つ並列に作って真ん中に草を生えるのを抑えてそれが正しいと言っていた。

  　八百重屋敷の2階からその慌ただしい道路の往来の向こうの左に目をやると大きな太鼓を備えた１５メートル程の櫓が立っていた。

  その櫓は盆踊りのためにあるように思われた。

  後にこの櫓は出太鼓という当時の農作業の区切りの時間を伝えるものだとわかった。

  当時の農作業では10:00時に太鼓がなって家に帰る、12:00,14:00 一日４回の食事を行う。

  いずれこの出太鼓は有線放送に置き換わった。

  　筆者はくされて朽ちた櫓の足のみ残っているのを小学校低学年までみていた。

  宗像地方には大手の炭鉱である三池や筑豊の資本が入り赤間,宗像,大福などの炭鉱が操業していたが国の石油へのエネルギー政策転換もあいまって、この数年後には宗像炭鉱も閉山となった。

  　ななみはおじいちゃんおばあちゃんの家を探したがそれらしいものは存在しなかった。

  だが朝の空気はこの前きた時と違い遥かに清々しく美味しいと感じたがその下の層には人々の生活の匂いはしっかりと漂っていた。

  田園が広がる先ににぽつんぽつんと茅葺屋根をつけた家があった。

  この地方の茅葺屋根は入母屋造といってツマの部分に木の格子をはめ込んで煙を抜くようにしている。

  その細煙は家々の人々が生きている存在を断固として示していた。

  同時に大きな優しさをななみに与えた。

  　しずこやしょうこにしたがっていればここでの生活はできる。

  だがいつも一番にやって一番に終わる宿題ができない。

  ポケットのスマホは圏外で機能しないからママや友達や姉妹に連絡する方法もない。

  それを思うと美しい赤い滲んで太陽が今にも登りそうな景色をみて涙がこぼれ落ちた。

  　引き返して、手洗い場で顔を洗ってダンプの音で橋の方をみると、なつが声をかけた、なつは手拭いを顔に当て朝の洗顔をしてきたらしい。

 「あんたどうしてここにいるんだろう。私のみた限りあんたみたいな、しずこさんのいとこはいないよ。」

  ダンプがバス停の前でくるりと曲がって大きな音をたてて駅の方に登ったのを見ていった。

  なつはななみの不安な横顔をみて言った。

 「あのダンプはこの先の山から石炭が出ていてね。それを運んでいるんよ。

  あの大きなせんだんの木２つある前が雑貨屋になっていてそこの主人が元締めやっているんよ。

  もうそろそろで石炭は尽くすだろうっていわれているよ。」

  ななみがそこの手前にあるのはだれの家と問いた。

  なつは頷くようにして事情を抑えているといった風に掌を自分の胸にひらみかせて言った。

  「ぼろヒョロ長い家があるだろう道挟んで柿木が２本横に厠がたっているだろう。

   あそこはここらで乞食兄弟っていわれているみすぼらしい兄弟がすんでいるんだよ。」

  ななみ「乞食!いくつくらいの兄弟なの?」

  なつ「私たちと同じくらいだけどね。いつも母親と一緒なの。

  母親の顔はおっかないよ。兄は３つ上位,下は２つ下くらいだよ」

  なつは手拭いを振って返して部屋に帰った。

  ななみ「じっちゃんは乞食兄弟といわれていたのか」

  　ななみは思い出してきた乞食兄弟は、りきまる家と繋がりがあるんだ。

  私がりきまる家に行ったらまずいことになるかもしれない。

  しょうこのおなご衆と談笑を遮って、

 「しょうこ。わたしがりきまる家にいくの変わってくれる。なんとなくここが気に入ったのいいでしょう。」

  しょうこは軽く「いいけど。」と言った。

  　ななみはここにくる前と何かが違うと考えていた。

  朝起きたら前日に建てた予定にしたがって行動する、それが毎日毎日。面白いことも面白くないこともあって、それが毎日毎日。親や姉妹や友達や先生や通学に会う人々。

  そういう人たちとここの人たちはなんか違う。

  ななみはそれが時間と気づいた。

  時間の流れがここの人たちと違う、自分が速い。

  私は速い。超人的に速い。

  顔を洗うのも人の言葉を理解するのも全て速い。

  だから落ち込む時間もない。

  だから夢の中にいるんだと思っていた。

  一方しずこはまだ正式に八百重屋敷で勤めていないため、用山に戻っていた。
