* <2021-02-25 1Thu> ストーリー
  + ストーリー
    + 昭和12年(1937)兄４人姉１人弟１人の６人兄弟の末っ子として生まれる。
    + 父はすでに他界、母と年の離れた兄達に助けられ生活する。
    + 小学校高学年で不登校になり中学校はまともに行かない。
    + 昭和28年18歳の時,姉を頼って鹿児島県相良郡より福岡県宗像郡へ就職する。
      + 朝、日豊本線加治木より乗車、西鹿児島に到着
      + 鹿児島本線の西鹿児島駅より蒸気機関車にて東郷駅に６時間かけて到着する。
      + 夕刻東郷駅から路線バス神湊行きで桝丸バス停に到着する。
    + 農家(坂屋敷)のおなごしとして働く。
      + 煤のついた顔を姉に拭いてもらいお苑の隅で姉と簡素な食事をとる。
      + 姉と同じ布団で就寝する。
      + 姉とおなご衆として仕事をする。
    + 農家(力丸家)のおなごしとして働く。
      + 力丸家の主人と奥さんに可愛がられ福岡の父母とよぶ。
      + 永井家(向かえの長男：利雄)と見合い
      + 鹿児島帰省の度主人にかならず帰ってこいといわれる。
      + 主人が鹿児島にきて結婚の申込をする。
      + 結婚し一男二女を設ける。
    + 利雄は国鉄にコネで就職するが大酒飲みだった。
    + 現在のDVだが酒を飲まない時は良い夫で働き者だった、
      それに加え国鉄の勤務はシフトであるため酒乱が毎日続くことはないので
      離婚して子供をつれて生活するよりはましだと思っていた。
    + 道に面した貧しい茅葺の家での仕事は金気を含んだ水を濾過するためのポンプ
      押し,かまどでの飯炊き,五右衛門風呂への川の水汲み,薪集め,田植え,草取り
      畑仕事,稲刈りなど炊事から農作業全てと子育てをした。
      そして肥をすくって肥たんごにいれて畑にまく肥たんご担ぎだった。
* <2021-02-25 Thu> 取材
  - 取材
    + 九州鉄道記念館
    + 195x の鹿児島本線の情報をえようとして門司までいったが情報コーナーが
      コロナで閉鎖されていて使えず。
  - 遠賀川温泉
    + 民家の横の道に5,6台の駐車設備を備えた民家を銭湯の小さなものにした風呂屋。
    + 玄関開けると民家の３倍位の敷居があって6x7位の下駄箱ロッカーが目にはだかって
      背けって足元に目をやるとこの狭い８畳程の板張りに足跡のマークが順路を誘発して
      しばらく立って客のガラガラドアを開ける音に気づいた無愛想な親父が自分の時間を
      じゃまされたように声をかける。
      「ロッカーは金いらんよ。」
      「そこの熱はかるやつで熱測って！」
      下駄箱ロッカーで塞がる壁の横に応接らしき部屋が見え、そのたちきり壁に
      なんやら体温を図る縦長の長方形の玄関ドアホンに似た物が壁に埋めてある
      顔を近づけ温度の反応をみるが反応せず、
      「真ん中のカメラに頭をひっつけるようにして。」
      その声に従うと縦横二三センチの青と赤の安っぽいランプが点灯して37.2と
      デジタルが表示される。
      それでオーケーになったんで、
      「入湯券をそこの自動販売機で買ってください」
      粗末な自動販売機に大人ひとり700円ふたり1400円とつづくボタンがある。
      タオルを忘れていたのでタオルはと聞くと下にタオル250円のボタンがあった。
      それを押してどこかoの病院で血圧測った時に出てくる熱転写の紙のようなものが
      でてくる、それをカウンター一面にはったビニールの上にだした花柄のお盆に
      のせろと親父がうながす。
      金気の湯。
  - にいちゃん、いのししとりにくる
    + にいちゃんなたをもってくる。
    + 2021-11-1からの猟を手伝うとのこと。
    + 免許は取らんでいい。
      
  - かーちゃんの人生(1937-2020)[(満年齢)]    
    + 1937(0),1938(1),1939(2),1940(3),1941(4),1942(5),1943(6),
    + 1944(7),1945(8),1946(9),1947(10),1948(11),1949(12),
      小学校
    + 1950(13),1951(14),1952(15),
      中学校,
    + 1953(16),1954(17),
      家事手伝い
    + 1955(18),1956(19),1957(20),1958(21),1959(22),
      おなご衆(福岡)
    + 1960(23),
      結婚
    + 1961(24),1962(25)(りきまる家建て替え),1963(26),
      長男
    + 1964(27),1965(28),
      次女
    + 1966(29),1967(30),
      三女
    + 1968(31),1969(32),　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　1970(33),1971(34),
    + 1972(35),1973(36),1974(37),1975(38),1976(39),
    + 1977(40),1978(41),1979(42),1980(43),1981(44),1982(45),
    + 1983(46),1984(47),1985(48),1986(49),1987(50),1988(51),
    + 1989(52),
    + 1990(53),1991(54),1992(55),1993(56),1994(57),1995(58),
    + 1996(59),1997(60),1998(61),1999(62),2000(63),
    + 2001(64),2002(65),2003(66),
    + 2004(67),
    + 2005(68),2006(69),2007(70),2008(71),2009(72),2010(73),
    + 2011(74),2012(75),2013(76),2014(77),2015(78),
    + 2016(79),2017(80),2018(81),2019(82),
    + 2020-08-22.12:55(83) (saturday)
      血圧がなくなった。
  - かーちゃんのアプリ
    母親と年代シミュレーション

* <2021-02-28 Sun> 肥たんご担ぎ
  + 肥たんご担ぎ
    1. 鹿児島から福岡(18歳だと聞いた記憶のちにしずこに確認18歳1955年昭和31)

	 九州最北の門司港から博多へと東から西へすすみ、筑後へ折れて、
         肥後へと南下したあと、八代を抜けて、薩摩の川内へ入りいくつもの山裾を縫って
         終点西鹿児島駅までの６時間半以上かかる九州縦断の鉄の道が当時の鹿児島本線である。
         ??? 特急は博多、小倉、門司の停車だからC59 1のような大きな蒸気機関車は東郷に停車していないはず。
         その終点の西鹿児島駅から、上り線、筑前のほぼ北九州と博多の中間にある東郷駅に客車五両を引いたC59 1が
         黒煙を舞上げ、ホームに白い水蒸気を撒きながら入線してきた。
	 汽笛がこの５月のよく透き通った青い空を震えさせた。

	 駅の隅には花壇が整備されていてもうツツジの花の淡い朱色をチラつかせている。
	 ホームの横の駅舎はガラス張りの木窓が薄く貼り付けられ中央に左右が
	 入口と出口と一緒の改札の駅員がこちらを向いて小さなおかっぱ頭の少女に
	 目配せをして案内をさせようとしていた。
	 少女は大きな風呂敷を首に回して長い旅で顔いっぱいに煤をつけていた。
	 煤のない細い目の周りだけを点滅させてあたりをおどおどと見回しながら
	 かろうじてモンペのポケットから探し出した切符を駅員に手渡した。
         駅員の改札パンチのカチカチ音の小気味良い音をすぎて待合椅子のならぶ
         駅舎に入るなり「しょっこちゃんこっちこっち」と若い女の声がした。
	 そこには妹を福岡まで呼びよせた姉のしずこが待っていた。
	「がんばったね、よくきたね」しずこは妹の荷物をやさしく抱いてうけとった。
	 姉は待合椅子に妹を座らせ手拭いで本人も気づいていない顔いっぱいの煤を拭いてやった。 

	 東郷駅のある宗像は黒田藩御用金鉱が全盛期だったため町には活気があった。
	 というよりは金鉱は隠蔽され地元住民もしらないものが多かった。
	 むしろ庶民には炭鉱が大井と池野に二つあったことによるものが大きかった。
         太平洋戦争も戦況の不利が見え始め内需拡大政策から炭鉱開発への補助金
         目当てに大井炭鉱も開発され宇部興産の資本と人員が入り込んでいた。
     	 その炭坑夫の落とす金を目的に居酒屋やカフェーの類もちらほら見受けられ
	 町では流行りの映画館も数件あった。
	 二人がいる駅の北側は緩い下り道となっていてその先まで商店がならんでいた。

	 二人はバスの時間を確かめた後待ち時間の間にうどんを啜ることにした。
	 駅舎のうどん屋は立ち食いだったが北九州では評判のよい東筑軒がやっていた。
	 姉はかしわうどんを二つたのんで置いてあるやかんから湯呑みにお茶をついだ。
	 「よくきたね、つかれたやろう」
	 妹のしょうこは気丈に答えた
	 「そうでもなかったけど博多駅の乗り換えで迷った」
	 しばらくしてうどんが目の前にでてきた。
	 しずこは「こしゅ(とうがらし)をこっちじゃ'こしょう'って言うんよ」と
	 いいながら一振り妹のうどんにかけてやった。
	 しょうこはかしわの匂いに少しけげんさを抱いたがこれが美味しいんだと
	 改めて異郷にきたことをかき消すようにをうどんをすくった。
	 横にいる姉と何ヶ月ぶりかに一緒に食べることことがうどんをすくうたびに
	 嬉しさにかわっていった。
	 そして不安の胃に流し込むうどんにみたされて、
	 うまれてはじめて一人で乗った汽車の出来事を振り返った。

    2. 朝の回想

	 今朝はいつもの鶏が騒ぎ出す前に薄暗い障子越の光と共に母親の手で起こされた。
	 眠いのと昨日兄たちの別れの宴で舞い上がり調子にのったのを悔いた倦怠で母
	 を見起こしたがもう姉のもとにいくことは決心の絶対としていたので諦めて
	 腕でまぶたを拭いた。
	 母はいつもより早めに起きて朝のめざめの味噌汁の匂いを子供たちに与えていた。
	 しょうこは起きて自分の役目である弟を探した。
	 足元に布団をはみ出し、身勝手な足を布団からはみ出し、服従の印の
	 しょうこの足のにおいをかいでるらしいさちおがいた。
	 このかわいい弟は今日限りすべてから解放され男としていきてゆく。
	 やっぱりやめたい。さちおがいるからここにいたいと叫びたかったがもうもどれない。
	 そして別れが来た、しょうこは涙を流さなかった、母ちゃんは涙を浮かべていたが
	 長兄がしきりをしていた、しずこがいるしだれもがしょうこの幸福を疑わなかった。
	 ただ、さちおだけはその別れの意味を切実に惜しんでいた。

	 しょうこは長兄と二人の最寄りの日豊本線の加治木駅へと向かうことになった。
         長兄はこれからの長旅を考えて加治木に向かう煙草を運ぶ牛車に乗せてもらう
         算段をしていた待ち合わせは役場の前だった。
         ふたりは役場前まで歩いた、しょうこの荷物は着物と着替えなどをいれる
         と風呂敷に大つつみとなった。それをもって兄は末妹のためその未来を信じて歩いた。
         牛車はまだついてはなかったが程なく牛のなく声とともにやってきた。
         牛車での10kmの道のりは5時に出発して２時間を超えて7時をまわっていた。
         ??? 当時でも路線バスが溝辺-加治木(14.5kn)(日豊本線),溝辺-嘉例川(4km)(肥薩線)で運行しているので書き換える方がいいかも　3/21
         
	 定刻通り西鹿児島への汽車を確認してしょうこの土産のカルカンを買って
	 しょうこの風呂敷に入れてやった。
	 「しょうこよ。ぜったい、くじけて帰ってくるんじゃないよ、頑張ってな。」
	 しょうこは兄の言葉を心に刻んだ。
	 西鹿児島までは小一時間で着いた。
	 鹿児島本線の特急かいもん博多門司ゆきはあと３０分後だった。
	 この西鹿児島駅では大きな風呂敷を抱えた若い女は珍しい光景ではなかった。

	 しかし、しょうこは今朝母ちゃんが握ってくれたにぎりめしと高菜の漬物に水筒だけが頼りだった。
	 このひとりで福岡に何時間も客車に乗って頑張れるんだろうか、便所をなんども
	 行き来して待った。
	 にぎりめしと高菜の漬物に水筒。水筒は２番目のにいちゃんの自慢の水筒だった。
	 溝辺の水をいれているんで死ぬまで飲むなと冗談を言われていた。
	 死ぬ間際に飲むと溝辺に戻って帰ってこれるよ。
	 そうも言われていた。

    3. 朝の回想(セーラー服の少女)

	 鹿児島本線特急はやぶさ博多・門司港ゆきの定刻になった。
	 汽笛が構内に響いた。
	 三等の切符は機関車のすぐ後ろだったが一番後尾の待合にいたので
	 車掌に前に行けと促され重い荷物を振りながら機関車の後ろの客車
	 に乗り込んだ。
	 席をさがすとさすがに始点だから空いている。自由席にして正解だった。
	 あんどで一番ひろいだろう対面席に荷物を置いて進行方向に向かって
	 座った。安心したこれでねーちゃんのところに行ける。
	 あとはお昼にかあちゃんの握り飯食ってにいちゃんの水飲めばいいだけだ。
	 先頭の機関車の轟音は客車の椅子や床まで震え上がらせる。
	 安堵は恐怖と家族の希望が合いまみれ朝早く起こされた眠気をかき消して
	 窓に肘をついて気取りなんかをよそう。

	 ふと目を車内にうつすと４列向かい席の対にひとりのセーラー服の少女が
	 いる。少女はもしかしたら同じくらいの年かもしれない。
	 その目は驚きに開いてどこを見ているかわからない。
	 気でも違うのかとおもうが身なりは整然と気品さえもっている。
       
	 私は今家族との別れと自分の将来への旅立ちにいるので人のことに関わり合う
	 立場にない。そう思ってしばらくすると眠りに着いた。

	 客車には機関車のたちこめる煙でいっぱいになっているのでそれで起こされた
	 と思ったが、さきの少女が肩を叩いていた。
	 「この指輪はあなたのものではないですか」
	 みると翡翠のような青緑の石がついている銀色の指輪だった。
	 それが欲しいと思ったが、違うというと、あなたの席にあったという。
	 どういうことかと尋ねると。
	 さっき空席だった時に拾ったら次の瞬間あなたがそこにいたという。
	 「あんたあたまがおかしいんじゃないの」
	 さき程の綺麗なセーラー服は煤けて顔も煤けてなぜかこれ以上とがめる気がしない。
	 「ここに座って」というと
	 「いいよ」といって座った。
	 しょうこは今朝母に起こされてまだ眠たいまま眠っていたからまだ夢の中にいる。
	 だがここで正義を尽くさねば兄たちが怒る。
	 しかたないこれに付き合って夢見るよ。
	 「あんたなまえは」「ななみ」「あたししょうこ」
	 「どこから」「くまもと」「あたしかごしま」
	 機関車の先頭客席は煙を舞い込んで石炭の匂いが立ち込め眠りを誘い込んだ。
	 めざめたしょうこは前の席に眠るさきの少女をみた。
	 動かなくなった汽車は駅について「日吉」のアナウンスを響かせていた。
	 そしてまた眠りについた。
	 しょうこは「筑前新宮」のアナウンスが響いて起こされた。
	 目の前にはまだ少女がいた。
	 少女の肩を揺らして、「どこまでいくの」と叫んだ。
	 少女は女の顔みて笑った。
	 「あんたもおんなじもんよ、東郷で降りるけど」
	 少女は人差し指にある指輪を目の前に出して
	 「この指輪はなん」「しらん」
	 「この機関車はもしかしたらC591」「しらん」
	 「わたしも降りる」「なんで」
       東郷駅に汽車が着いた頃しょうこは降りて改札をさがしていた。
       このセーラー服の少女はどこかへ消えてしまっていた。

    4. 東郷駅での騒動

       しょうことしずこはうどんを食べ終わった。
       すると駅員の大きな声で駅員とその向こうに見えるセーラー服の少女を見返った。
       しょうこは「やっぱりあの子降りたんだ」とうどんの箸で差した。
       「日吉あたりからあの子が私にからんできたんよ。」
       しょうこはうどんをおいて駆け寄って、この子は私のいとこで一緒に汽車に乗ったが
       切符をどこかに忘れて探していたがついに見つからなかったと言い訳をした。
       さっきはトイレにいたから別々に改札と通うったのだとも言った。
       それは鹿児島弁だから駅員は度肝を抜かれたが引き下がらない。
       意を理解したしずこも加わり鹿児島弁で駅員をねじ伏せ少女を無理やり改札口を通過させた。
       駅舎でバスを待つ間、二人はななみに問いただすがななみにもどうしてここいるのかわからない
       二人は警察に届けるべきかと悩んだが笑みやら声の調子からなにかしらの親近な情を思わせる
       ものがあったのでこのままいとことしてしょうこと一緒にまぎれておなご衆として
       やっていけるのではないかと考えた。
       主人は寛大というか何事にも頓着しない人だと思っていたから使用人がひとり増えても
       気にならないだろうと思った。
       むしろのこのななみの方が心配になった。
       ななみはななみで人差し指につけた指輪がとれず苦労しているだけのこれもほけのようなもの
       と思われた。

    5. 坂屋敷

       ??? そもそも坂屋敷にはいっていない。
       ???しずこはいつの時点か不明だが中山八百重(やおじゅう)家にいっている
       ???中山泉のちに朝倉出身の絹枝と結婚
       ３人のバスは東郷駅についていて出発の時刻を待っていた。
       ３人が乗ると車掌が妹の大きな風呂敷を取って空いている席においた。
       車掌は手についた煤に眉をひそめて払い次の乗客を見下ろした。
       その先には見たこともない紺の制服らしきものを着た少女がいかつい目
       で見上げた。車掌は肩からかけたガマ口の銀のつかみでを撫でてそれを
       いなした。少女に切符を切ってバスの後部に促した。
       そのあと車掌は乗客を数人乗せて切符を切ると運転手に促したのち車掌席に座った。
       姉妹と少女は仲良よさそうに席に座ったていた。
       運転手は何かを呟いて、鼻の突き出たバスをキュルキュルとセルを回してエンジンを起こした。
       ３人を乗せたバスは東郷駅から商店街をくだって左に大きな池を左に見て山中へと
       入ろう坂を登り始めると右手には羽色のコンクリートが低木の茂みから見え隠れして
       何やら建物があるのがわかった。
      「あれは火病院といって伝染病患者がはいっている病院よ。あそこには絶対入らなでよ。」
       姉は３つ年下の妹の怖気を面白がっていった。
       左手の山の中腹に小さな池をみてバスは迂回しようとしていた時姉はまた続けた。
       「あの池向こうに煙突がみえるでしょう。あれは火葬場よ。」
       妹は不安になり前席の黒いバーを握りしめた。
       ななみはその妹の手をつついて硬さを確かめていた。
       バスは火葬場と火病院の横を抜けるゆっくりと下りだし火病院をすぎて手付かずの低木
       が茂山には爽快な新緑をまとっていた。
       左方の広葉樹の山も新緑が広がっていたがバス道から横に走る砂利道数本あり
       民家の存在を予見していたしょうこは果たして自分がこれから世話になる家が
       いつ出現するのか期待が湧いてくるのを感じた。
       バス道はいよいよ下り坂が急になり両脇の山が開けるのと同時に一本のまっすぐの
       道になった時両脇に刈田が大きく開いて周りに集落があるのを見た時ここがこれから
       生活していくところとわかった。
       バスは直線が終わったところで泊まり姉は妹についたことを肩で教えた。
       車掌に風呂敷荷物をもってもらいながら３人はバス停に降りた。
       車掌はななみに荷物がないからなお風呂敷が重いものだと決め付けていた。
       バス停の横には道幅は5m程のちいさな川ながれてその横の道が上流へと続いて
       もうすでに葉桜となった桜の並木が少しきつくなった日差しの木漏れ日をじゃりの
       道に現していた。
       姉は妹にすぐに見える橋を指差しそれから道を指でなぞってその先にある丘の上
       の屋敷で止めた。
       「あそこが坂屋敷あそこで仕事するんよ」
       その橋を渡って川を折り返すと数件の集落が続いてその左手に坂屋敷に登るゆるやかな
       道の入り口があり両側には良く整った畑があり白菜や高菜の類が並んでいた。
       坂屋敷は大きな合掌作りの茅葺の屋敷を正面に右にいなやとよばれる作業倉庫
       があった。そこには見たこともない吹子などが格納されてその端には牛小屋があり
       庭の端には鶏小屋があった。
       牛と鶏の糞尿の匂いは無風の中でも帯が閃くように漂っていた。

    7. 坂屋敷2

       ななみは自分がどこにいるのかわかってきた修学旅行の最中だったのだ。
       新型コロナの影響で熊本の近県である福岡県に決まった時全校生はため息にどよめいた。
       熊本をバス４台で朝９時に出発し九州高速道路を門司インターまで走らせたついたのが
       １０時すぎだった。
       北九州の門司港レトロタウンを散策するまえ九州鉄道博物館を順回していたが
       展示された蒸気機関車C591の客車に回った時対面の席に背もたれと座席の間に
       埋めっている指輪を見つけた、その指輪を認めた時から時間を遡ってはやくも
       65年ほどタムスリップしているのだ。
       二人の姉妹がだれかもわかっているばあちゃんとばあちゃんの姉の二人だ。
       ななみには未来からきたことでこの世界は歴史の趨勢からみても生活はかなり落ちるものだと思っていた。
       しかしここの生活はいきなり他国にいくほどのギャップがあった。
       物理的な有利はほとんどなく、しょうこより２つ年下ゆえの下っ端として
       しか扱われないこともわかっていた。
       昨日勉強していたのは安土桃山だったから全然やくにたたない。
       ?? ここの描写要考慮

       玄関を開けて姉が奥に入り女主人を連れてきた。小さな素朴な顔をした女だったが
       かぶとい声を使って「遠いところ良くきたね」と労い。
       姉は「いとこがひとり増えた」といったが知り合いにおなご衆をもとめているものは
       おおいので安心するように言い払った。
       姉に部屋についって着替えて夕食の準備を一緒するようにいった。
       おなご衆の部屋は２階にあった、大きな土間と板間の横の階段を軋ませてあるくと
       一番奥に部屋があった。姉が先に入ると二人のおなご衆が小さな台を挟んで休んでいた。
       姉より年上の二人はなつとふみといった。
       ?? 何人おなごしがいたか調査(力丸家は３人だった)
       妹といとこを紹介するとさもない冗談をいって笑いが一瞬湧立ったがその後は静かになった。
       なつが「鹿児島はもう暑いのか」と尋ねたが、
       しょうこは「寒い」と答えて、風呂敷の中からおみやげのカルカンを取り出した。
       そして姉に二つ渡した。
       しょうこを送り出す時その長男が地元の日豊本線加治木駅のキヨスクで
       カルカンのみやげを二つ持たせてあったのだ。
       ふみが「またカルカンか」といってしずこから取り上げた。
       ふみは近隣の集落からきていたが数カ所の屋敷を追い出されそのおりにつけ鹿児島
       おなご衆と土産にカルカンをもらっていた。
       なつとふみはしずこより先輩であり二年前からの付き合いなので気心は知れている中
       であるがふみだけは早くどこかに行けと思っている。
       部屋は六畳間に一軒の押入れそこに布団と彼女たちの持ち物が入っている。
       部屋には火鉢とみすぼらしい鏡台とちゃぶ台があるのみである。

       しょうこたちはここに4人で暮らすことになる。
       しずこは同じくおなご衆で働いていたが場所は大井川をずっと登った上流に
       ある用山の豪農の屋敷で働いてた。
       しょうこの挨拶がすんでしょうこの身支度をすませると用山に帰ることになっていた。
       しかしいとこのななみが増えたので主人に相談したかった。

       しょうこはななみがなにもたべていないのか気になった。
       ななみは朝熊本で食事をしたきりだった。
       おしくも途中で食べようとしたおにぎりが残っていたので渡したら
       ななみは美味しそうに食べた、あまりにも腹が減ったので水筒の水を
       要求した、そして一挙に喉に流し込んだ。
       食べっぷりがここらにない男のような食べ方をしたななみをみて
       なつとふみは不思議に思った。
       まもなくして夕食と風呂の準備がはじまり５人は降りていった。
       ななみにはみなと同じ飛白の着物と同じ飛白のモンペに割烹着だった。

       しずこは明日の夜くると主人に伝え、しょうことななみをよろしくと頼んだ。
       主人「うちは人では一人でいいんだ、明日どちらかをただしさんのところへ行ってもらうよ。
       今決めようじゃんけんしな。」
       しょうことななみはジャンケンしてななみが勝った。
       主人「じゃあななみがただしさんのところだな。」
       ななみ「ただしさんのところちかいんですか」
       主人「ちょうど田んぼをはさんだ目の前の大きな石垣の家だよ。大きなイチョウの木が何本も植えてあるよ。」
       ななみを優しく見下ろしみんなに「それじゃみんなよろしくな。」
       しょうこもななみも突然違うところで働くところが違って不安を書き立てたが近いので
       安心もしていた。
       くど係、ふろ係、調理係、配膳係、清掃係、子守係。２名だったがこれから3人
       でまわせるのでよいと思われた。
       めし、ふろ、配膳では３人でおとこ衆と主人と女主人を切り盛りする必要がある。
       田植えは６月の梅雨入りにおこなわれるがそれまでには荒手さらいなどの部落行事を
       行う必要がある。
       荒手さらいは近隣の農家から出方をだして共同で水田の溝の掃除をする行事である。
       この当時はそこで取れる鯉やフナなど馳走として食卓に花を揃えるので獲るたのしみ
       も加えて若い男女の社交の場ともなる。
       ??? 記述が幼い
       このあたりの農家の作りはくど作りといって飯を炊いたりするくどが最低でも２つあり
       この坂屋敷にはくどは３台あった、台所の間のと食事をする板場、さらに隠しとびらで仕切られた
       風呂とが隣接している。
       風呂はクドの大きいもので下から薪をくべる水は男と女でそれぞれ変えて入るのが原則
       だが農作業の忙しい時はそれもなおざりになることも多い。
       食事は主人とその子、おとこ衆、おなご衆と順になっており、山作業や農作業には
       あとでおなご衆の握ったにぎり飯や漬物を届けるようになっている。
       ???つけもののレシピも後々いれるので調査

    8. 景色の中の乞食兄弟

       ななみは坂屋敷の2階から大井の景色を見下ろしていた。
       ??? 時間的矛盾はないかな?
       坂屋敷から小さな大井川を上流に桜並木を辿ると４つ橋がかかって
       一番奥の端から小型のダンプが黒煙を上げて川に沿った道を下って
       坂屋敷橋から道路に出ては東郷駅の方に向かってはまた遠くの橋を
       渡るということを繰り返していた。
       ダンプには黒い石のようなものつまり石炭が積まれていた。
       そのダンプのため古い桜の枝葉は拒んで切られて通るのを助けていた。
       道は穴ぼこだらけでいたるところに雨水をためてはタイヤでひかれ乾いて補修の不揃いの砂利が埋められていた。
       その補修が愛ではなく諦めのものだった。
       ダンプはワダチを二つ並列に作って真ん中に草を生えるのを抑えてそれが正しいと言っていた。
       坂屋敷の2階からその慌ただしい道路の往来の向こうの左に目をやると大きな太鼓
       を備えた１５メートル程の櫓が立っていた。その櫓は盆踊りのためにあるように思われた。
       後にこの櫓は出太鼓という当時の農作業の区切りの時間を伝えるものだとわかった。
       当時の農作業では10:00時に太鼓がなって家に帰る、12:00,14:00 一日４回の食事を行う。
       いずれこの出太鼓は有線放送に置き換わった。
       筆者はくされて朽ちた櫓の足のみ残っているのを小学校低学年までみていた。

       宗像地方には大手の炭鉱である三池や筑豊の資本が入り赤間,宗像,大福などの炭鉱が操業していたが
       国の石油へのエネルギー政策転換もあいまって、この数年後には宗像炭鉱も閉山となった。

       ななみはおじいちゃんおばあちゃんの家を探したがそれらしいものは存在しなかった。
       だが朝の空気はこの前きた時と違い遥かに清々しく美味しいと感じたが
       その下の層には人々の生活の匂いはしっかりと漂っていた。
       田園が広がる先ににぽつんぽつんと茅葺屋根をつけた家があった。
       この地方の茅葺屋根は入母屋造といってツマの部分に木の格子をはめ込んで煙を抜くようにしている。
       その細煙は家々の人々が生きている存在を断固として示していた。
       同時に大きな優しさをななみに与えた。

       しずこやしょうこにしたがっていればここでの生活はできる。
       だがいつも一番にやって一番に終わる宿題ができない。
       ポケットのスマホは圏外で機能しないからママや友達や姉妹に連絡する方法もない。
       それを思うと美しい赤い滲んで太陽が今にも登りそうな景色をみて涙がこぼれ落ちた。

       なつが声をかけた、なつは手拭いを顔に当て朝の洗顔をしてきたらしい。
       「あんたどうしてここにいるんだろう。私のみた限りあんたみたいな、しずこさんのいとこはいないよ。」
       ダンプがバス停の前でくるりと曲がって大きな音をたてて駅の方に登ったのを見ていった。
       なつはななみの不安な横顔をみて言った。
       「あのダンプはこの先の山から石炭が出ていてね。それを運んでいるんよ。
       あの大きなせんだんの木２つある前が雑貨屋になっていてそこの主人が元締めやっているんよ。
       もうそろそろで石炭は尽くすだろうっていわれているよ。」
       ななみがそこの手前にあるのはだれの家と問いた。
       なつは頷くようにして事情を抑えているといった風に掌を自分の胸にひらみかせて言った。
       「ぼろヒョロ長い家があるだろう道挟んで柿木が２本横に厠がたっているだろう。
       あそこはここらで乞食兄弟っていわれているみすぼらしい兄弟がすんでいるんだよ。」
       ななみ「乞食!いくつくらいの兄弟なの?」
       なつ「私たちと同じくらいだけどね。いつも母親と一緒なの。
       母親の顔はおっかないよ。兄は３つ上位,下は２つ下くらいだよ」
       なつは手拭いを振って返して部屋に帰った。
       ななみ「じっちゃんは乞食兄弟といわれていたのか」

       ななみは思い出してきた乞食兄弟は、りきまる家と繋がりがあるんだ。
       私がりきまる家に行ったらまずいことになるかもしれない。
       まだ寝ていたしょうこを起こして
       「しょうこ。わたしがりきまる家にいくの変わってくれる。なんとなくここが気に入ったの
       いいでしょう。」
       しょうこはもう一度布団をかぶって「いいよ。」と言った。

       ななみはここにくる前と何かが違うと考えていた。
       朝起きたら前日に建てた予定にしたがって行動する、
       それが毎日毎日。面白いことも面白くないこともあって、
       それが毎日毎日。親や姉妹や友達や先生や通学に会う人々。
       そういう人たちとここの人たちはなんか違う。
       ななみはそれが時間と気づいた。
       時間の流れがここの人たちと違う、自分が速い。
       私は速い。超人的に速い。
       顔を洗うのも人の言葉を理解するのも全て速い。
       だから落ち込む時間もない。
       だから夢の中にいるんだと思っていた。

       一方しずこは昨日は遅いので坂屋敷にしょうこたち４人で泊めてそのまま暗がりの中,用山に帰っていった。

    9. おなご衆

       しずこは坂屋敷を出るときに牛や鶏の世話をしているおとこ衆
       に用山に帰ると告げて、まだダンプは通っていない凸凹した道を歩いていた。
       途中に例の乞食兄弟の家の横をとおった。
       あらためてみるとこの家は結構長い。
       牛小屋から始まり、いなやから風呂とクドと土間1と食場そして敷居があって座敷がある。
       座敷は３つ道路沿いに続いて最後に焚物小屋がその集めた薪をあましている。
       ガラス格子の枠は所々折れてガラスもヒビが入って割れている中は外からでも雑然と
       して片付けができていないのがよくわかる。
       玄関は２枚の引き戸になっているが、なんだか傾いている。
       そして最後に斜めに落ちる階段があってその横に狭い庭がある。
       その庭はとても小さいがよく剪定された松や牧の木などがありところどころに花咲かせた
       優しさを訴える植物が散りばめられている。
       次元の違う世界がこの小さな坂に造られている。
       よく配置され階段の段々の降り先に小さな池まで見えた、こんな小さな空間にどれだけ
       の努力でこの庭を維持しているのだろうか。
       その庭を見下ろして足を止めて見たが周りの人の目が気になって止めて帰路を急いだ。
       用山まで小一時間だが山を登らないといけないが庭の横には雑貨屋がある、この家は
       道に沿って長く張り付くのではなく逆に垂直に伸びる家ここは炭鉱の元締めと荒い
       子分の休む場所になっている。
       まだ人気はないので安心して横をすぎてまだ川沿いの道をいく。
       川の流れはすこし厳しくなって左側は崖が張り出し、しがみついている木々が川を
       覆ってその下の流れが右へと蛇行して用山の山の中へと入り込んでいる。
       ここを中左に折れて緩い山道に入る、山道はうっすら暗闇の帷をおろしている。
       この難所を過ぎればまた左に折れて川沿いに戻り木造の５間ほどの橋をわたる。
       そうすればしずこのが奉公している屋敷の屋根が見える。
       しずこが奉公する屋敷はよしだ家で用山の部落では一番立派な通り門を備えている。
       この屋敷は黒栖様を祀っている山の麓にある。
       通り門は門の左右上部がいな屋か住居になっておりその下の空間を人や荷馬車が通る
       ようになっている門のことである。

       前方には北西に広がる刈田の平野でも日の光さしてきてが暖かさを広げてがっていた。

       ここまできて安心したので妹のしょうこのことを考えた。

       私は1934年生まれの戌年、しょうこは３つ下の1937年丑年。干支はこどもの頃から
       そういう性格なんだと思っていた私はいつもキャンキャン騒いでいるしるし、しょうこ
       はおっとりしている。だから中学を出ても母ちゃんの横で家事手伝いやら兄たちの
       世話をしているのではこれでは先がないと思って福岡に誘って世間を教えてあげなければ
       と決心してそれが昨日実現した。
       だがかわいい妹の人生に関わったことがどうなるのか。もうなんども考えたがそれが
       いいと思ったからそれでいいとまた納得した。
       よしだの屋敷に帰りついた。大きな声で挨拶をして部屋へあがろうとしたら最近色目を
       使ってきているおとこ衆の一人が声をかけてきた。
       「どうだった妹は無事についか。橋をわたるのがみえたよ。妹はこっちに連れてきてないんだ。
	どんな妹なんだ。」
       しずこはこの男が嫌いだったので「お前には関係ねー。かつよさんはどこにいる？」
       女主人に話をしたかった。「ふん。子供の世話で部屋にいるよ。」
       部屋に戻っていつもの支度をしてクド場にいって水をしゃくっていっぱいのんだ。
       主人の部屋の奥にすり足でいって障子越しに「しずこです、ただいま帰りました。」
       女主人の反応は少し遅れて「妹さんは無事に坂屋敷についたんだね。」
       しずこは答えた。「それがもうひとりいとこを連れてきたんです。ひとつ二つ下ですから１７歳くらいです。」
       こどもをあやしながらいった。「おなごしはどこでも必要だからいいんだけど親御さんはわかってらっしゃるのかい。」
       しずこはななみの人柄には不思議な安心があったので「それは大丈夫です。
       明日は朝の仕事終わったらもう一度大井にいってきます。」と答えた。
       女主人に今日は下の女の子がぐづついているので一緒に寝てくれと言われた。
       クド場にもどると他のおなご衆は妹といとこがきたことをしっていた。
       あいつが立ち聞きしていたらしい。
       この日女のあかちゃんを抱いて４人で眠った。あかちゃんは数えの２つだった。
       しずこはなんども夜泣きで起こされその都度他のおなご衆にもんくをいわれた。
       この赤ちゃんは他のおなご衆には懐かなかった、しずこの子守唄にだけ安らかな顔でねた。
       しずこの子守唄はおはら節だった。
       花は霧島
       煙草は国分
       燃えて上がるは桜島
         桜島には霞がかかる
         わたしゃ おはんに気がかかる
       咲いた桜に つなぐな駒を
       駒がいさめば花が散る
         みえたみえたよ 松原越しに
         丸に十の字の帆が見えた

    10. 黒切り

        しずこが奉公する十年前に大井で事故が起こっていた。

        各部落で共用の山地や水溝の整備のために各家庭から作業員を出すことになっている。
        その中のひとつである黒切りが春の浅い日に行われた。
        いつもなら男手を出す予定だったがその日は牛の競のため
        まさおは現在宗像消防署がある場所に立っていた畜産市場に行っていた。
        仕方ないので嫁のしんが黒切りの作業に山に入っていた。
        出方を出さないとペナルティーを課せられるしくみだったので止むを得ない状況だった。

        運の悪く母親がまだ恋しい10歳のやすおが学校から帰宅したところ母親がいないので兄たちに聞くと
        山に黒切りに行っているということなので兄たち一緒に遊びがてら山に入っていった。
        小高い丘の上に立つ５軒の茅葺屋根の民家があってその横を抜けると孟宗竹の林が
        たちこめゆっくりと山の中腹に入る道が現れる３人の子供は慣れた足付きで黒切り
        の作業場を探したがもっと奥で作業しているらしい。
       
        大井の田園がひろがる道の横に水神様と里の人が呼ぶ小さな池がある。
        今は朽ちているがレンガで囲いの残骸がありその周囲には２・３本の松と1本の柳の木があった。
        この柳の木を切ると怪我人がでるとか死人がでるとかの言い伝えがあって、
        部落のだれもが知っている。
        今年の初冬その柳が枯れた。

        やすおは母を追って山に入ったが兄や弟に置いていかれて不安を覚えていた。
        ４月とはいえ深い木立に空さえ遮られているので肌寒い。ふと横に目をやると小さな水の
        流れを発見した。蟹や魚がいるかもしれない。その流れを隠すように大きな岩があったので
        それによじ登って覗こうとした。
        登り終えたと同じに岩が崩れてやすおは放り出されてその岩の下敷きになった。
        やすおの叫び声と石が重い音を立てるを聞いた兄と弟は駆け寄ってやすおが岩の下敷き
        なっているのを見つけた。
        弟のかつおはなすすべなく立ち尽くし「かあーちゃん」と泣きさけんだ。
        兄のとしおは大人を探すべく山を登って行ってほどなくして大人を数人つれてきた。
        大人は木の枝を切ってテコでなんとかやすおを引き出したがやすおは絶命していた。
        兄のとしおは再び母親を伴って現れた。
        母は泣き崩れた。
        やすおは学校で一番の頭の良さでだれもが認めるような神童だった。
        特に算数はずば抜けていてたびたび先生を驚かせていた。
        なんでもすぐに理解できオルガンも教えてもらえなくとも弾くことができた。
        生徒はそのマジックに驚いてやすおはうわさの渦中にもあった。
        やすおの目は透き通っていて眉は太く大きくきりりと終端を勇しくピンと上げて
        天性の才能と華奢なはかなさが女子生徒には憧れになっていた。
        ただ薄幸な唇は悲しさを漂わせていたがその隙間から白い歯がのぞむと
        多くの女生徒はこの男を自分のものにしたいと願っていた。

        母親の口癖は「うちらは人前のことはできん」だった。 
        兄はとしおと言って、弟はかつおと言った。
        彼らが乞食兄弟である。そしてその３番目の兄弟が死んだ。
        この兄弟は男ばかり６人の兄弟であった。
        母は山形県米沢市の生まれである、かの上杉鷹山に使えた中級武士の子孫として
        姉ひとりの二人姉妹として育った。
        家督を相続したいと山形県置賜郡佐沢から婿養子を迎えた。
        明治後半から武士の子として埃はあったが家は極貧しており山形の冬の厳しさ
        から逃がれたいと渇望していた。
        妹のしんは山形でまもなく３人の男の子を授かったが兄ふたりとも病気で夭折させてしまった。
        奇妙なことに３人目の子供を産み下ろした同じ日に父をなくした。
        1934-5-7のことである。父の命日を誕生日にもらった子供がこの乞食兄弟の兄としおである。
       
        しんは極貧の厳しさと偶然に翻弄され胃潰瘍を患って痩せ細っていた。
        亭主は鈍感だがやさしく働き者だったがいっこうに極貧の生活は改善されず、
        二人の子供も失って絶望していた、そんな中姉は男好きのする女で器量も立つので
        男をあてに福岡のこの地に流れ着いていた。
        そして妹の不幸を嘆いてこの地に呼び寄せていたのだ。
        残った一人の５歳の息子をつれて姉を頼ってこの地についていた。
        この大井で200円で家と牛を買って借りた田畑で作物を作り、北九州の黒崎に行商した。
        宗像では３人の男の子をもうけた。都合４人の男の子の兄弟ができた。
        そして今日10歳を迎えた子供を奪われ３人の兄弟になったのだ。
        遺体を家に運んでいつも寝ている汚い布団に寝かせた。近所の夫人会が東郷から医者を呼んで
        警察の対応を済ませてくれた。母親は寝かせた布団の横で首を垂れすすり泣いていた。
        その時育てた牛を売って思わぬ程の収入を得た夫のまさおが帰ってきた。
        まさおは家の前に止まっている警察車両や出入りする近所の人を見てあたふたしたが
        としおとかつおが駆け寄ってきたのでやすおがいないことをわかった。
        「やすおが死んだのか」と呟いた。
        近所のしんぺいが説明して座敷へと寄り添って連れてきた。
        しんは帰ってきた夫を見上げて「なんであんたが黒切りにいかんやった!」と
        責め立てて泣き伏せた。
        割烹着姿の婦人会たちからもすすり泣く声が聞こえた。
        まさおは泣き叫び伏せて震えるしんの肩に手をやってやすおの枕元に座った。
        やすおの顔伏せの白い布をとって顔をなでまわして言った。

        「朝はあげん元気やった。もう好きな餅もくえんとじゃな。」

        1945年浅い春のとてもいい天気の夕刻のことだった。

        東京大空襲の噂は部落に広まって、日本は負けるそんな情勢の中の出来事だった。
        現実として住民をさらに憔悴させたのは６月の福岡大空襲で福岡市の４分の1以上が消失していたことだった。
        疎開して親類のあるこの部落のだれぞのかの噂しかなかったがこの平穏な村でもB52の唸る
        爆音を聞くことがあったので村の人々にも暗雲な不安が広がっていた。
        そしていよいよ不安を増したこの家族にはどん底だったが、それはまだどん底ではなかった。
        1945-8-6 広島と1945-8-9 長崎に落ちたものがなんなのか東郷の居酒屋などで話題にでるが
        だれもわからなかった。
        ??? GHQ 1945-9-19言論統制のためのプレスコード発令

        生まれて５歳になった末っ子のただおはだれよりもまさおに似ていた。
        まさおは食うことがが心情の男だった、山形県東置賜群の佐沢で三男として生まれ
        食い扶持減らしで米沢の通町のしんの婿養子になった。
        手先が器用で竹細工やら庭づくりやら盆栽の手入れなど周りが驚く程の才能を見せていた。
        末っ子のただおはしんとまさおに特に可愛がられた。
        やすおの事故の反動もあったのかもしれないがとにかく二人はただおを可愛がった。
        まさおはしんを愛していたというよりは尊敬の念さえもっていた、気丈な性格、
        すっきりした顔立ちから発する声とその音の散りばめられた空鍋に蓋の水滴が弾いたような
        声のかすれの中に飛び出すとても心地よくかつ怪訝でもありその飛沫の煌めき奥のごく
        弱いがはっきり私に信頼と日本がどう動いてもいい性欲こそが新しい命を繋げてくれる。

        しんは知っていた。ただおとそれを愛すためのものがこの世の中で大勢の中でも二人の
        愛は今後の家庭で収入も上がっていく、牛の選びはよいしあと６ヶ月かければこの牛は
        ２倍の売値をつげるだろう。牛のビジネスにのぞみが出てきて少し生活は楽に向かいそうに見えた。

        やすおの49日が終わる頃学校から帰ってきたただおは母親に腹痛と吐き気を訴えてた、額から汗が滲んでいたため
        急遽往診を呼んだ。医者は赤痢の疑いがあるので和歌の病院につれていくように進めた。
        ??? ここはつながっってない
        夫婦で火病院(??火病院のじが間違っている)にただおをだきはこんだ。

        看護師はたらいに乳白色の洗浄剤を作って家族全員に手をあらわせて、念のため
        病院で全員の検査を行うように段取りをとりつけた。
        幸い家族には感染者は出ず、ただおだけが入院隔離となった。

        暑い夏がきた。
        1945年5月20日～23日は10°まで下がるという稀な初夏の気象だったので尚更この暑い夏が不気味だった。

        火病院へは歩いて20分だったが感染症がゆえ面会は拒絶された、受付で看護師を
        よんで様子を聞くだけだった。衣類も食料も渡すことはできなかった。
        1945-8-13ポツダム宣言受諾の前日に病院により電話がありただおは危篤と知らせ
        がきた。その夜同時に火葬にしたのでお骨を取りにこいと連絡が入った。
        ??? 1964-6から有線電話放送が各家庭に配布だから電話はない、区長宅設置の黒電話のからの人による伝達としてよいかも
        再びこの家族は鎮痛な葬式を迎えることになった。
        やすおと違ってすでにお骨となったただおが仏壇に置かれていた。
        そのまま通夜が家族で行われた。
        翌日の正午のサイレンがならされ公民館には村の民が押しかけていた。
        玉院放送を聞くためだった。
        ??? この描写だれかに聞いてもっと現実味をだせないかな
        その夜、まさおとしんの両親、としおとかつおの兄弟二人、
        ４人の家族はいい知れない不幸に諦めを噛み締めて抱き合って寝た。

        暑い夜にすり減り黄色がかった濃緑色の吊るした蚊帳と蛾のまとわる薄暗い電灯だけがこの家族を守っていた。

        この時期さがせばどこにもこのような不幸は存在した。
        水神様の柳が枯れたから起こったと言いふらすものもいた。
        この話は隣村の用山村でも伝えられた。そして10年たってもしずこにまで届いていた。

    11. りきまる家,子守,縁談
	バス通の火病院の山を下り切ると500mの直線が伸びる、その先に坂屋敷がある。
	直線の始まりから左に折れる小道が見え始めると十力のバス停がある。
	この地域は十力と言いりきまる姓の家が多いその中に高い石垣に囲まれた
	屋敷があるそれがりきまる家の本家である。
	数本の大きな銀杏の木と石垣の中央に長方形の刳抜があり石が安置されている。
	???一説によるとその石はこの大井を最初に作った山伏を祀っているらしい。
	?? 庚申塔
	しょうこが女子衆勤めることになるりきまる家は、現在の家の入り口ではなく
	弧を描いた石垣が終わったところに入り口があったここは牛車でも登ることを
	難儀する坂だった。
	坂を登ると左には稲屋(いなや)があり農耕器具や収穫した作物倉などがあり
	味噌小屋、漬物小屋あり、奥に茅葺屋根入母屋があった。

    12. 結納,結婚,子供
    13. 肥たんご担ぎ
    14. 宗像の食べ物
    15. ななみタイムスリップ
    16. 新しい家
    17. 子供の成長
    18. 子供の親離れ
    19. 孫
    20. 子供の回帰
    21. 闘病
    22. 死
    23. 死のあと

* <2021-03-01 Mon> 爺さん情報
  - 炭鉱
    + いけの炭鉱
    + おおい炭鉱
      + ボタ置き場、しげみ、登記しときゃー長谷川の名義
    + 
  - じじい(21-03-01)
    しずこは用山におった
    ばあさんは坂屋敷にはおらん。むかえにおった。
  - じじい(21-03-27)
    迎えの石垣は昔からあったが現在の道はなくて表がわに玄関へと
    道があって急坂は馬車で登るのは苦労した。
  - 過去にいくと時間が早く進む。
  - 力丸キミコ(多礼)は力丸信重の姉=力丸家分家
* <2021-03-04 木> 死と花
  + 火葬を終えて肉体が完全になくなった後,その人の生前の姿が少しずつ
    あらわになってくるたびどういう意味があるのだろうと知恵を使って
    その示し方がどうも仏のような英知を感じるとき仏になった死んだ人
    を崇めてしまう。
    だからそれが死人を仏ということだと思う。
* <2021-03-04 木> 肥たんご担ぎ
  + あたしゃこれしか人生ありせんと。
    肥をすくってたんごにいれてかつぐ。
    もう一本肥たんごの棒は肩に食い込んでよれるよ。
    すくった肥たんごは畑にまくよ。まいたら土をかける。
    これが私のしごと、くる日もくる日こ肥えたんご担ぎ。
  + あたしゃこれしか人生ありせんと。
    はやく肥たんごくまんとみんながこまる。
    もう一本肥たんごの棒は肩に食い込んでよれるよ。
    すくった肥たんごは畑にまくよ。まいたら土をかける。
    これが私のしごと、くる日もくる日こ肥えたんご担ぎ。
  + あたしゃこれしか人生ありせんと。
    肥をためればうじがわいてくる。
    もう一本肥たんごの棒は肩に食い込んでよれるよ。
    すくった肥たんごは畑にまくよ。まいたら土をかける。
    これが私のしごと、くる日もくる日こ肥えたんご担ぎ。
* <2021-03-06 土>
 + 三谷幸喜(イザベラ・バードの日本紀行)
   + 1878-6-9日本奥地紀行として執筆(明治11)
   + ノミみまみれ,障子の穴からたくさんの目
   + 男はガニ股、女はよろよろ歩く,152cm,滑稽,青い短い股引,
   + 日光街道：日本は美しい
   + 大阿川,日光金谷邸
   + 日本の子供は小さな大人,竹製の虫かごにキリギリスを飼っている。
   + 松たか子のナレーションもあってすごく綺麗な日本語だと
    幸せに浸ってしまうかもしれないがこれは日本語ではない。
    イギリス人女性による英語的な日本語である。
* <2021-03-07 日> 一回忌楽曲
  + 1937-5 美空ひばりと同じ歳生まれの一つ学級上
  + 1936-10 北島三郎と同級
  + 1937-1 江利チエミと同級
  + 選択楽曲
    1. 江利チエミ<テネシー・ワルツ>
    2. 美空ひばり<りんご追分>
    3. 森昌子<せんせい>
    4. 森昌子<悲しみ本線日本海>
    5. 森昌子<越冬燕>
    6. 石川さゆり<天城越え>
    7. 石川さゆり<津軽海峡・冬景色>
    8. 美空ひばり<ラブイズオーバー>
    9. 北島三郎<北の漁場>
    10. 天童よしみ<川の流れのように>
* <2021-03-10 水> 参考資料
 + 宗像市史 通史編 大三巻 近現代 H11
   + 1936-12 東郷町に常設キネマ館東宝館開設
   + 1937-7-7 日中戦争始まる
   + 1938-4-1 国家総動員法公布
   + 1938-4-10 灯火管制規制実施
   + 1941-6-1 米配給制(345g/1日/1人)
   + 1941-12-8 太平洋戦争始まる
   + 1942-2-1 味噌醤油配給,衣料は点数制
   + 1944-6-16 B29北九州を初爆撃
   + 1945-3-9 東京大空襲
   + 1945-6-19 福岡大空襲
   + 1945-8-6 広島に原子爆弾投下
   + 1945-8-9 長崎に原子爆弾投下
   + 1945-8-14 ポツダム宣言受諾
   + 1945-8-15 太平洋戦争終わる
   + 1946-11-3 日本国憲法公布
   + 1949-4-25 １ドル360円
   + 1949-8-17 ジュディス台風河東地区冠水
   + 1950-6-25 朝鮮戦争始まる
   + 1950-8-10 警察予備隊令公布施行
   + 1951-1-30 西鉄ライオンズ結成
   + 1953-6-25 北九州豪雨
   + 1954-3-20 志賀島金印国宝
   + 1954 ５町村合併による宗像町誕生
   + 1954-4-1 宗像町誕生(吉武,赤間,河東,南郷,東郷,1神興)
   + 1956-6-1 玄海国定公園
   + 1956-7-21 光岡八幡宮くすのき県天然記念物
   + 1956-7-28 山田横山観音堂くすのき県天然記念物
   + 1956-11-1 西鉄ライオンズ優勝
   + 1957-6-26 東郷山笠中止
   + 1957-8-1 宗像町営有線放送全域で開始
   + 1957-11-1 西鉄ライオンズ優勝
   + 1957-12-11 百円硬貨発行
   + 1958-3-9 関門国道開通
   + 1958-4-1 自転車税,荷車税廃止
   + 1958-11-1 西鉄ライオンズ３連続優勝
   + 1958-12-1 1万円札発行
   + 1959-4-10 皇太子の結婚式
   + 1959-7-1 赤間,東郷小学校プール完成
   + 1959-7-14 豪雨で東郷に濁流水深2.0m自衛隊出動
   + 1959-9-26 福間競馬廃止
   + 1961-1-7 雪のため東郷橋付近で300台立ち往生
   + 1961-6-1 鹿児島本線門司港-久留米間電化
   + 1961-10-8 東郷地区商店街水銀灯完成
   + 1964-9-1  有線放送各戸に電話器取り付け(s50-3廃止)
   + 1964-10-1  NHK福岡カラー放送
   + 1964-10-10  東京オリンピック開催
   + 1964 牛や馬から耕運機に
   + 1965-2-7  米ベトナム北爆撃開始
   + 1965-6-6  宗像電報電話局開設自動電話化
   + 1966-2-3  ソ連ルナ9号月面軟着陸成功
   + 1966-7-1  豪雨のため城山峠土砂崩れ
   + 1966-11-1  八所神社イチイガシ,トキワガキ県天然記念物
   + 1966-11-22 部落解放運動の松本治一郎死去
   + 1967-11-7  東郷中央映劇閉鎖映画館０
   + 1967-8-1  交通違反反則金制度
   + 1968-2-7  大井ダム建設着工
   + 1969-4-1  宗像七町塵芥処理場操業開始
   + 1969-6-10  GNP世界二位
   + 1969-10-1  交通違反制度実施
   + 1971-12-20  国道３号線宗像香椎バイパス開通
   + 1972-2-3  札幌オリンピック開幕
   + 1972-3-15  大阪岡山山陽新幹線開通
   + 1973-11-14  関門海峡開通
   + 1973  石油ショック
   + 1974-10-17  光岡ライスセンター完成
   + 1975-3-10  山陽新幹線岡山博多開通
   + 1978 渇水 平均14時間の給水制限のべ287日
   + 1984 宗像終末処理場増設
   + 1994 渇水 平均8時間の給水制限のべ295日
 + 溝辺町郷土史 溝辺町郷土史編纂員昭和48
   + 迷信(溝辺につたわる)
     全国に同じ
     
 + 宗像伝説風土記上下 上妻国雄
   + 黒尊(くろずみ)さま
     用山
   + 水神さまの柳
     大井
   + 平和(ひらとも)さまと和宗(ともむね)さま
       大井には平家落武者伝説が残っている。
       平家が壇ノ浦の合戦に破れ一門の平和(ひらとも)様と知宗(ともむね)様もこの宗像の里まで落ち延びてきた。
       幾日か詫びしい里山の奥の暮らしをしていたがある時源氏の追手が現れた。
       用山と大井の低山の境に逃がれた平和(ひらとも)様は眼下に源氏の白旗が田畑になびくをみて
       「今日限りの命ぞ」と観念して潔く自害された。
       同じく知宗(ともむね)様は大井と田島の境で自害された。
       里の人々はこの二人の武将を菩提をともらってそれぞれに石祠を建てて祀っている。
       -> 
* <2021-03-14 Sun>
 + 家系
   + 永井　ちよ(1951-1927年6月26日)(76歳)金吾の妻
   + 永井　はる(1931年11月28日)新の姉

   + 永井　幸一(-1933年8月3日)
   + 永井　誠(-1934年8月24日)

   + 永井　金吾(-1934年5月7日)

   + 永井　安雄(1935-1945年4月6日)(10歳)
   + 永井　忠雄(1940-1945年8月13日)(5歳)

   + 永井　新(1900-1970年1月3日)(70歳)
   + 永井　雅雄(1904-2-3-1980年11月27日)(76歳)

   + 永井　昌子(1937-3-20-2020年8月22日)(83歳)
   + 永井　勝雄(1939-2-14-2020年8月29日)(80歳)
 + 家系
   + 岩元 フデ(1986)(83歳)
* <2021-03-29 Mon>
  + 国立国会図書館のオンラインサービスにとうろく
    nagaihart@gamil.com
  + 永井 利一 様

インターネット限定利用者登録が完了しました。
あなたの利用者IDはE13426044です。
登録情報の確認・変更は、国立国会図書館検索・申込オンラインサービス（国立国会図書館オンライン）にログインし、利用者情報のページから行ってください。
https://ndlonline.ndl.go.jp/#!/user/

国立国会図書館への入館や館内での各種サービスの利用には、別途カード発行等の手続が必要です。
本人確認書類と利用者IDをお持ちください。

━━━━━━━━━━━━━━━
国立国会図書館 関西館 文献提供課 複写貸出係
Tel：0774-98-1313

本メールの送信アドレスは送信専用です。返信メールには回答できませんのでご了承ください。
━━━━━━━━━━━━━━━
  + 田熊でやっていた花火大会の記述もいれるべき(摩利支天神社の記憶?)
    東京墨田の花火は見物客は路上に座る習慣があるがおそらく福岡にはないはず。
    この記述もいれたい。(要調査)
  + 
* <2021-03-31 Wed>
  + 黄砂昨日は記憶にないくらいひどい。
    目に見えないこの粒と新型コロナの粒で日本人を貶めているらしい。
    
* <2021-04-02 Fri>
 + 1全国時刻表　1957年10月号(昭和32/10)　全国列車時刻大改正号
   + https://page.auctions.yahoo.co.jp/jp/auction/q429524618
* <2021-04-04 Sun>　食いもん
 1. 鏡餅
 2. たらの胃ひもの(正月)
 3. 味噌(味噌越が必要)
 4. 梅干し(梅酢漬け)
 5. らっきょ漬け
 6. 梅酒
 7. へらくち酒(ここらではまむしのことをへらくちという)
 8. おきゅうと
 9. ソーメンのり
 10. 塩卵焼き
 11. チマキ
 12. のうさば(ウチでは食っていない)
 13. がめのは饅頭
 14. だご汁
 15. いなり寿司
 16. メリケン粉をこねたざらざらした甘い切り餅のようなもの(不明)
 17. ちゃづけ(さば)
 18. サバの大根煮
 19. たくわん
 20. マカロニサラダりんご入り
 21. 高菜の漬物
 22. 高菜の漬物の炒め物
 23. ちゃわんむし
 24. 肥前漬け(いつからか不明:家で味噌をつけなくなってからか)
 25. 雑煮
 26. だご餅、きな粉餅
 27. 蒸しパン
 28. カレー粉と缶詰(鯨大和煮)
 29. 鳥のすき焼き
* <2021-04-04 Sun>
 + 博多駅
   + ２代目
     + ルネサンス様式(今の門司港駅に似る)
     + 1963-12-8に移転
     + 1909年(M42)-1963年取り壊される
   + 3代目
     + 現在の博多駅
     + 1963 完成
   + H23博多シティー
 + 博多駅
   しょうこが到着した博多駅は第２代目である。ルネサンス様式として1909(明治42年)年建築され、
   現在の地下鉄祇園付近の大博通りを縦断して中央に駅舎を構えていた。
   1963年(昭和38)に壊されて現在の博多シティーの位置に移転するまで
   九州第一の都市の玄関として人々の暮らしを支えていた。
   くらしというより時代を支えていた、遠賀川流域の赤線地帯から送られる日本人たち彼女らは女は戦地には送ることが
   できたいので物資として博多港から送られてきた。彼女らは日本人の従軍慰安婦だった。
   おおくの復員兵は博多港に到着した後この博多駅から全国の我が家に帰って行った。
   駅舎の特徴は中央にドーム型の窓が３つ並び中央の窓の上方に三角の屋根
   少し小さい屋根を左右の端に乗せて柱もアーチ構造をいくつも取り入れていた。
   時代を半世紀も支えてきたルネサンス建築は"きっぷうりば"や日本食堂を
   立てましされて高度成長時代の要求を少しずつ変化に表していた。
   駅舎内には鉄道弘済会売店も有していたがKIOSK=キヨスクと名前は変えるまであと15年(1973)も
   有することになる。
   第２代博多駅は３面のホームと５線を有した九州最古の駅のひとつであった。
   駅舎の中央の改札口を出ると第1プラットホームが東西に伸びてその両端に
   第2・第3プラットホームへの連絡橋が備わっている。
   各ホームにはスレートの屋根を連絡橋の階段まで覆っている。
   乗り入れは門司港-鹿児島間の鹿児島本線のみである。
   篠栗線はまだ乗り入れていない。
   博多口にあたる駅前は西鉄の路面電車やバス、人や貨物のための車両で賑わっていた。

   ???以下はないが３番線に入線したと思われる。
   鹿児島本線快速鈍足は門司港方面への登り線1番線が第1プラットホームに接して連絡階段を
   使って鳥栖久留米方面の下り線が2番線となる。
   門司港-西鹿児島間の特急は上り線は第2プラットホームの3番線に入線し
   次の駅の小倉へと向かい、下り線は第3プラットホームの4番線
   使って次の駅の鳥栖へ向かう。
 + 九州鉄道
   + 1872-10-14(新橋-横浜)日本初鉄道
   + 1887(M20)-6九州鉄道会社結成
   + 1889-12(博多-千歳)九州初鉄道
   + 1890-9(博多-赤間)
   + 1891-7(門司-熊本)
   + 1907-4国有鉄道化
   + 1927鹿児島本線全複線化
   + 1913-4(T2)東郷駅開設

* <2021-04-06 Tue>
  + 
* <2021-04-06 Tue>
  + KBC
    + https://www.youtube.com/watch?v=lBzo0Za7Eso
      + 博多駅の普通列車は１番線
* <2021-04-07 Wed>
  + 宗像むかしの生活研究(第六号) 特集-住居と家族・親族
    + 須恵の石松豊彦の赤牛
    + スズメの子を屋根葺屋根の瓦で見つける。
      先人は手乗りスズメとして飼うこともあったらしい。
    + 田の字型の日本の農家の典型
    + いろりは大正初期に廃れた
    + 長男をオヤカタとよび農作業の指揮官していた
    + 中座敷,奥座敷,板の間,台所
    + こえだめは畑などに作られた肥を集める穴
    + こえたご(肥桶)担ぎは中学校で実習させられていた
    + スカブラ(働かない人),スカボラ。
    + 藁で編んだ籠(ソラクチ)
    + 牛に与える餌の桶(ダオケ),だのみず(こめのとぎ汁)
    + 火吹き竹
    + 住居は北と西向きには建てない
    + 屋敷に植えない木(理由)
      + 藤(家を巻き倒す),ビワ(茂って邪魔),孟宗(根がはりまくる),イチジク(花がない),ソテツ(養分の鉄分を食う),柿(家の中の金をかき出す),
    + お稲荷様=家が不幸続き,病人が多い
    + 長男(そうりょう),若い嫁(ゴリョンサン),男衆(名前をよぶ),女子衆(ねーちゃん)
    + 産婆さん(へそばばさん)は八日結いで親族,兄弟,近所と招いて馳走する
    + 大正九年ころ電灯がつく
    + クドには平たい鉄の蛇の目(リング)がついている
    + 中小のクドにはどうこ(銅壺)という鉄製で中が空洞で水をいれるとお湯が沸く
    + 茅葺の屋根を葺くときは広島から職人がきていた、カヤは良いものは再利用,足りない時は小麦の藁でを混ぜて使う,隣近所が加勢(かせい)にくる
    + 用山(130年前は60戸)
      + そてつ(金食い虫),銀杏,ゆずりは(暮れに葉をとられ裸になる）
      + ４尺の竹を締めて垣根にして屋敷を
      + とおりもん(わきや(作業場,農機具倉庫,牛小屋)の梁のしたが通り抜けられる)
      + たきもんごや(焚き物小屋)
      + にわ(土間),左ずまい(左にナカイ),右ずまい(右にナカイ),ないしょ(食事をするところ)
      + 屋根は入母屋造でツマの部分に木の格子をはめ込んで煙を抜くようにしている。
  + 宗像むかしの生活研究(第二号) 結婚式と葬式
    + 済み酒
      縁談の話が進み承諾されるとすみ酒(一生一代=一升一鯛)一升瓶と目の下１尺の鯛を持って仲人が嫁のところへいく
    + 結納
      + 伊勢こよみにより大安吉日にて結納決定
      + 品物(総じてお茶という)
        茶着物,帯,白足袋,表付き履きもんなどを三(宝)方(神前に供するための祭器具)に乗せてだす
    + 結婚式
      + 婿方の家で行った
      + としお,しょうこ,仲人,それぞれの兄弟,子供
	+ (かつお),(フデ,とおる,きょうこ,しずこ,みちよ,あきお,かずゆき)
      + 仲人の家から嫁にでる
    + 今では訪れなくなった人
      + 福神売り
	大黒様と恵比寿様の泥焼きを正月になると戯けた調子で売りにくる
	数がおおくなると氏神さまにあげるどこの社にもいっぱいある
      + 鋳掛け屋(いかけや)	  
	穴の開いた鍋底を修理する
* <2021-04-08 Thu>　食いもん
  + 正月
    + 鏡餅
    + たらの胃ひもの(正月・盆)
    + がめ煮
      材料:鳥モモ,レンコン,こんにゃく,ゴボウ,里芋,大根,人参,干し椎茸
      料理:醤油,砂糖,酒
  + 味噌(味噌越が必要,秋)
  + 梅干し(梅酢漬け:５月)
  + らっきょ漬け(5月)
  + 梅酒(5月)
  + へらくち酒 (6月-)
  + おきゅうと(-)
  + ソーメンのり(4,5月)
  + 塩卵焼き(-)
  + チマキ(5月)
  + のうさば(ウチでは食っていない)
  + がめのは饅頭(正月,盆)
  + だご汁
  + いなり寿司(秋)
  + のりまき寿司(秋)
  + メリケン粉をこねたざらざらした甘い切り餅のようなもの(不明)
  + ちゃづけ(さば)(-)
  + サバの大根煮(夏)
  + たくわん
  + マカロニサラダりんご入り(-)
  + 高菜の漬物(?)
  + 高菜の漬物の炒め物(?)
  + ちゃわんむし(-)
  + 肥前漬け(いつからか不明:家で味噌をつけなくなってからか)(-)
  + 雑煮(正月)
  + だご餅、きな粉餅(彼岸)
  + 蒸しパン(-)
  + カレー粉と缶詰(鯨大和煮)(-)
  + 鳥のすき焼き(冬)
* <2021-04-09 Fri> 時刻表(1958-10)
  1. 加治木までバスがあるはず
     + 竹子-溝辺下十文字-下有川-布越-加治木駅が南国交通(???)
  2. 加治木[日豊本線]1958-10
     + 加治木(8:55)
     + 鹿児島(9:20-9:29)
     + 西鹿児島(9:35)
  3. 特急はやぶさ(No.10)[鹿児島本線]1958-10
     + 西鹿児島(10:40)
     + 八代(13:40)
     + 熊本(14:14-14:18)はやぶさ
     + 大牟田(15:07-15:05)
     + 久留米(15:39-15:40)
     + 鳥栖(-)
     + 博多(16:12-16:20)
       - 博多(17:17)鈍行
       - 東郷(17:55)
     + 折尾(-)
     + 門司(17:28-17:32)
     + 門司港(||)
* <2021-04-10 Sat>
  + ななみの携帯がすべて圏外でほとんどのアプリが使用できない
    + バッテリーが9%になったので来るべき時のために電源を切って保存する方法をとる
      + google レンズが使えるので。
      + なんかのアプリが小説中にでてきてもおもしろい
    + 携帯は来るべき時のためにひらとも様の石の社の屋根と壁の隙間に差して
      保存しておく。
    + ぶんじろうが片目になったお袋さんのために戦争が終わっても生きて返してくれ
      と祈願してそれが成就して生きて帰ってこれた。
      その文次郎が故郷に帰った月日にお参りを欠かしていないということで一緒にのぼる。
    + 出太鼓は村のどこにいても聞こえた。
      そしてここにいる限り時計が必要なかった。
      当時の時計がなんであったか調べる必要がある。
      ゼンマイ式時計か。
  + 修学旅行列車
    + ２人x３人掛シート(104人のり),縦型網戸,世界初の男子トイレ
      + きぼう,わかくさ,わこうど,とびうめ,こまどり,
      + S49-10廃止
* <2021-04-10 Sat> google の商的検索でなく文化的検索が必要
  + 商の反対の言葉
* <2021-04-12 Mon> かあちゃんはきれいなワンピースできた
  + お袋が貧しい鹿児島の田舎から時代が戦後からの復興を漲らせた時代
  + そこに憧れてこの福岡と北九州の間の田舎の寒村にきたわけじゃない。
  + シンデレラとして舞い降りたんだ。

* <2021-04-14 Wed>
  + 吉田釣具のばーちゃん(87歳)
    + いつ死んでもいいように洋服も買われん。
    + 桝丸橋渡って左にいって２番目、今はもう梅の木しかない。
    + みのるさんの横
    + 姑さんが厳しくて泣いていたのを加工場でうちのばあちゃんによく慰めてもらっていた。
    + 辛抱しきれず家をでた。
    + 今の吉田釣具の田んぼを３００坪買ってよく働いた。
    + だから今がある。
* <2021-04-15 Thu>
  + 出太鼓
    + 5:00 朝食
    + 10:00 太鼓 昼飯 休憩
    + 11:00 太鼓 作業
    + 14:00 太鼓 食事(小昼)
    + 目が見えるまで作業
    + 晩飯
 
* <2021-04-18 Sun> 硬貨歴史
 + 1953年（昭和30年）貨幣単位「銭」が廃止され、単位が「円」のみとなる。
 + 1955年（昭和30年）6月1日：現行1円硬貨流通開始。素材はアルミニウム。
 + 1955年（昭和30年）9月1日：50円硬貨流通開始。素材はニッケル。図柄は菊の花一輪。
 + 1957年（昭和32年）12月11日：100円硬貨流通開始。素材は銀。図柄は鳳凰。
 + 1959年（昭和34年）2月16日：現行10円硬貨流通開始（側面の溝の無い新しいデザインに変更）。
 + 1959年（昭和34年）2月16日：100円硬貨の図柄が鳳凰から稲穂へと変更される。
 + 1959年（昭和34年）2月16日：50円硬貨のデザインを穴の空いた形状へ変更する。
 + 1959年（昭和34年）9月1日：現行5円硬貨流通開始（字体を旧字体から新字体、楷書体からゴシック体へ変更）。
 + 1967年（昭和42年）2月1日：現行100円硬貨流通開始（素材が銀→白銅へ、図柄も桜の花三輪へと変更）。
 + 1967年（昭和42年）2月1日：現行50円硬貨流通開始（素材がニッケル→白銅へ変更、デザイン変更、直径縮小）。
 + 1982年（昭和57年）4月1日：500円硬貨流通開始。素材は白銅。
 + 2000年（平成12年）8月1日：現行500円硬貨流通開始（偽造防止を図るため、素材をニッケル黄銅とし、デザインを変更し、潜像を施した）。
 + 2021年度（令和3年度）下半期以降予定：偽造防止を図るため、500円硬貨の素材およびデザインを変更し、3層構造のバイカラー・クラッド硬貨となる予定。

 + <2021-04-18 Sun>
   + しょうこの食べ方は俯いて周りを伺いながら箸を動かす。
     この食べ方は幼い頃から兄たちから食い物を取られるためについた習性だった。
     ひとりで食べる時は解放されるため食い散らかす汚い食べ方をした。
 + <2021-04-18 Sun>
   + しょうこやじいさんを書くことでなくて、俺自身を書くことにしなくてはならない。
   + 一番わるいのはおれだった。
   + かあちゃんの１番の失望は俺だった。二位がじいさんだ。
   + ふところにだかれたときの匂いと安心がかあちゃんだった。
* <2021-04-19 Mon> 言論統制
  + WGIP
    + 戦後処理,
  + 1945-9 プレスコード発令
  + 1952-4-28 サンフランシスコ講和条約発行に従いプレスコード廃止
  + ダグラスマッカーサーは５歳まで女装,三男兄死ぬ親の溺愛によりマザコン
    + 13歳新聞配達
* <2021-05-01 Sat> ５月気温
 + オホーツク海の高気圧から流れ込む湿った北寄りの風の影響で、東京都心は、けさも雲が多く、冷え切った朝になりました。
   都心の午前9時までの最低気温は10.7度で、平年を4度ほど下回り、4月下旬並みになりました。
   5月下旬以降、夏にかけての最低気温が10度台または10度を下回ったのは、1988年5月23日(10.1度)と24日(9.8度)に観測して以来32年ぶりです。
   この時も2日続きましたが、きのうとけさも、これと肩を並べる冷え切った朝になりました。
   ちなみに、1945年以降で、最低気温が10度台または10度を下回る日が5月後半以降、夏にかけて連続したのは、(1)1945年5月20日～23日、(2)1946年5月24日～25日、(3)1966年5月23日～24日、(4)1973年5月23日～25日、(5)1988年5月23日～24日の5回だけです。
* <2021-05-20 Thu>
 + 力丸清一さんへの質問
   + 理由
     + お袋のことを孫やひ孫に残しておきたい
     + 宗像の風習や料理なども伝えて置きたい。
     + お袋の生まれのこと女衆しとしてどうやって生活していたのか
     + いくつで力丸家にお世話になってどうゆう生活していたのか
     + 結婚までの経緯などが知りたい

   + 内容
     + いつ力丸家にきたのか(二十歳だったと聞いたような)
     + 力丸家の部屋
     + 女子衆の名前
     + 力丸家の前の家の間取り、築年
     + 女子衆の仕事内容
     + 給料
     + 力丸家のイベント（女まつりなど）
     + 料理、漬物、一覧を書いているのでそれに付け加えたい
     + うちにある最古の写真は結婚式のものだけなんで、写真があれば見せていただきたい。
     + 力丸家の梅干しは梅酢漬けかどうか
     + 小麦粉を練ったもちのようなお菓子
* <2021-06-05 Sat>
  + 映画参照
    + 砂の器
      + 作品執筆と同時1960-61
      + 背広半袖刑事
      + 東北弁亀田
      + ハンセン病
      + S46国鉄総裁事件
      + 着物
      + フリルの着いた今風のワンピース
      + フロントバンパーミラー
      + ばあさんは灰色の前掛け鼠色のがらのワイシャツズボン
      + 茅葺の上にトタンを貼る農家と瓦屋根が混在していたのでは

* <2021-06-20 Sun> 2013に高菜漬けをしらべたテキスト発見した。
* 20120316 

高菜の塩漬け（２０１２年３月１５日開始）

１、高菜は切り取ってすぐに干す、干す時間は丸一日目安。
　　人によっては切りとってそのまま畑で干す人もいる。
　　ただし、雨には要注意です。
　　干す前に、大きいものは４分の１、普通以下は２分１に株から縦に
　　切り分けておく。
＃　　白菜の場合なら、切り取ってすぐに４分の１に切ってを水洗いしてから
＃　　丸一日干す。
　　高菜の大きさは３、４０cmのものがベストらしい、よんぱちなどの肥
　　により、固くなったりするらしい。
　　育て方はまた別途綴る。

２．これをよく振って泥や砂を取り除く。
　　
３．最初の塩揉みを行う。

　　高菜を横にして両手で握られるほど選んで、それに塩を振る。
　　塩は、一差し指、中指、薬指、小指の４本で軽く掴む程度。
　　もみ加減としては、絞って汁が落ちてくる程度までもむ。

４．これを樽に漬け込む

　　樽は、高菜の量によって決めるが、良く荒って、沸騰した湯を
　　まわしかけて消毒してもよい。
　　これに隙間がなくなるようにきっちりとつけ込んでいく。　
　　一段できたら、塩（例の４本指でつかんだ感じを）まんべんなく
　　振っていく。これを２度するようだ。
＃　　この際に近所の奥さんはニンニク（半分にきっているのか）をいれているらしい。
　　また、揉んだ時の塩が甘いと高菜がピーンと立ってくる場合もあるらしいので
　　重石の重さなど研究余地はある。
　　以後、同じく、隙間無く、高菜の量だけ段を重ねて行く。
　　桶に合った丸板を置き、重石（１２kgを２つ程）はきれいに洗ったものを使う。

5．これを２日から３日置いておくと塩が上がってくる。
　　この汁気は灰汁を含んでいるので一端、ざるに上げて汁気を切る。

　　この歳、一株ごと丁寧にとって水気を切っていも良いが気分で適当でもよいらしい。
　　ざるに上げてからは２時間程が目安である。

６．最後（２回目）のつけ込み。

　　さっきの樽を洗って使う。
　　とにかく隙間ができると虫の原因になるので隙間ができないように
　　注意して、１段目を作る。
　　最初のつけ込みと同様に塩だが最初より２回目を多くする。
　　最初と違うのは虫がつかないように胡椒（赤唐辛子を５mm位に切ったもので
　　たね込み）を５本（詳しく量はわからず）分位。１段毎に振っていく。
　　付け方は、最初と同じようにする。

　　１月なるかならないほどで青色から茶色へ変化する。
　　その間、汁が多くでていると酸っぱくなるのでタオルなどを使いとる。

７．最後のつけ込みから２日、3日で食べられるようになる。

  塩だしは、水は替えをやりながら、半日程水につけて行う。

　　塩の量にもよるが半年まで食べられる。

＃　　高菜は１月近くで熟成するのでその時々で味も変わるだろうが、夏は、
＃　　みそでも何でも開けられないらしい。

　　あの美味なる高菜のごま油傷めもこの夏をこさないとうまくならないだろう。

* <2021-08-03 Tue>
 + 力丸清一さんに電話
   + S27生まれ(1952)
   + 詳しく調べてみないとわからん
   + 女子衆三人
   + 小学校5/6年にうちが建て替わった。
     1952,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,67
     0   ,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16
   + 今とは母家といなやが逆の位置
   + 味噌小屋,漬物小屋とわかれていた。
   + こえたんごかつぎはむつこさんが一人でやっていた。
 + かあちゃんの年齢をもう一度確認
   昭和 9	1934	87	戌
   昭和 10	1935	86	亥
   昭和 11	1936	85	子
   昭和 12	1937	84	丑 0  1
   昭和 13	1938	83	寅 1  2
   昭和 14	1939	82	卯 2  3
   昭和 15	1940	81	辰 3  4 
   昭和 16	1941	80	巳 4  5
   昭和 17	1942	79	午 5  6
   昭和 18	1943	78	未 6  7
   昭和 19	1944	77	申 7  8
   昭和 20	1945	76	酉 8  9
   昭和 21	1946	75	戌 9  10
   昭和 22	1947	74	亥 10 11 
   昭和 23	1948	73	子 11 12
   昭和 24	1949	72	丑 12 13 たえこ
   昭和 25	1950	71	寅 13 14
   昭和 26	1951	70	卯 14 15 清和誕生
   昭和 27	1952	69	辰 15 16
   昭和 28	1953	68	巳 16 17
   昭和 29	1954	67	午 17 18 
   昭和 30	1955	66	未 18 19 上福　やおじゅうさん(しずこから)(30/11ともやす誕生)
   昭和 31	1956	65	申 19 20
   昭和 32	1957	64	酉 20 21
   昭和 33	1958	63	戌 21 22
   昭和 34	1959	62	亥 22 23
   昭和 35	1960	61	子 23 24 結婚
   昭和 36	1961	60	丑 24 25
   昭和 37	1962	59	寅 25 26 力丸家建て替え
   昭和 38	1963	58	卯 26
   昭和 39	1964	57	辰 27
     
* <2021-08-13 Fri>
 + 清和
   + 写真２枚
     + 力丸家の玄関の坂(みずえ,初枝)
     + むつこさんたちと旅行
* <2021-08-16 Mon>
  + 吉田直人さん
    人の名前をわかる範囲で記述
* <2021-09-11 Sat>
  + しずこおばちゃんと話す
    + やおじゅうさん
    + しょうこは二十歳じゃない18才で上福していると判明
    + 力丸家に直接奉公した
    + いずみさん
    + 用山にもいたが覚えていない。
* <2021-09-12 Sun>
 + 清和電話する
   + たえこ
   + ともやす30/11
   + 来年田んぼの苗してやる
     
* <2021-09-12 Sun>
 + ちえみ宗像来る
* <2022-03-16 Thu>
  + 文次郎の長女
    太郎とリードで散歩して梅の木に登らせていると家の前に不審なグレーの軽自動車が止まって
    なにやらやっている。
    電話でもしているのだろうと太郎を家にいれて木の剪定をしていたら後ろから声をかけられた。
    「この家の自転車にいつも乗っているおじさんはどうしていますか」
    近所の人がよく散歩で親父にあって、その後見ないのでよく尋ねてくる類だなと思った私は
    「去年11/8に亡くなりました」と色々と説明していると私のばあさんの新の話がでた。
    「ここのおばあちゃんが死んだ後すぐに私のばあちゃんも死んだんです」
    聴くと片目のばあさんのことだった。
    そしていろいろ話をしていると文次郎は海軍にいっていたので決まった戦地はないとのこと。
    これでななみと文次郎との関わりを想像する大きな手がかりが見えた。
    それにしても太郎との散歩もただの思いつき、不思議な偶然が呼び寄せた出会いだった。
* <2022-04-22 Fri>
  + ばあさんが18才で上福した時溝辺から加治木には南国バスを利用し55号線を下ったとの考察が濃厚になった
  + 加治木駅の現在の駅舎は小学校の時にばあちゃんの実家に里帰りに着いて行った時このような
    駅舎に夕方着いた記憶がかすかにあるような他の記憶からすり替えたような曖昧な映像が浮かんだ。
    だから前述のバスによる工程が濃厚との判断がより正しいと思わせる。
  + 加治木駅は1945年4月26日 - 加治木空襲により初代駅本屋焼失。
    とある、ばあさんから以前に聞いていた小学校校庭に爆弾が落ちていたとの話を思い出した。
    これは加治木空襲の際にダグラスA-20が沖縄から18機の編隊を組んで爆撃したその一部の機が溝辺の小学校
    に落としたのではないかと推測したがダグラスA-20の航続距離からマリアナ諸島のサイパンなどから
    はB-29の航続距離5000kmオーバーを持ってしか不可能だから沖縄から飛び立ったと想定したまでにとどまった。
    
* <2022-04-22 Fri>
  + 太平洋戦争と海上輸送
    太平洋戦争は、開戦に至るまでの経緯はともかく、直接的な動機は米英を中心とする連合国のわが国に対する経済封鎖、なかでもその殆どを米国に依存していた石油が、米国の　「対日石油全面禁輸」　によって確保出来なくなったことが、わが国が開戦に踏み切った最大の要因であった。
    したがって、資源のないわが国が開戦にあたってとった基本方針は、南方の資源地帯を占領し、そこから戦争遂行と国民生活に必要な石油、鉄鋼、非鉄金属、ゴム、ボーキサイトなどを確保するというものであった。
    開戦と同時に日本軍は、真珠湾の奇襲攻撃と同時に南方地域に進出その戦域は、西南太平洋全域におよび北はアリューシャン、東はミッドウェー、南はフィジー諸島を結んだ広大なものとなっていった。
    そして、この戦いを左右するカギは、いつにかかって海上輸送の確保にあった。その意味から太平洋戦争は、世界戦史に例を見ない大海洋作戦であった。
    しかし、その結果は、わが国商船隊の壊滅とともに日本の生命線は絶たれ、敗戦を迎えた。

    １ 開戦にあたってわが国の商船は総べて　「戦時海運管理令」　によって、一元的に管理された。
    ２ 保有船腹を軍の作戦行動と民需輸送にどう配分するかは、開戦に踏み切る前の重要課題であった。
       現有船腹でも、果たして海洋作戦が主力となるこの戦争に対処できるのかと言う不安があった中で、船舶を作戦と民需にどう振り分けるかは国家としての判断が問われた。結局、軍の強い発言力でそれぞれ２分の1　(300万トン)　ずつの配分となった。　ただし、緒戦が完了すれば、軍の徴用船の一部を民需に回すことで合意ができた。
    ３ 開戦後の船舶の被害は、緒戦の優勢であった一時期こそ僅かであったが、昭和17年6月、ミッドウェー海戦で米軍　(連合軍)　に敗北し、制空権、制海権を奪われ後退に転じてからは、敵の潜水艦や航空機の攻撃による喪失は予想をはるかに上回るものとなっていった。
       開戦に踏み切るかどうかを判断する政府首脳会議で、敵の攻撃による船舶の被害をどの程度に見るかが重要な議論となった。
       その時海軍が提出した船舶の喪失は、約年60万トンであった。これは確たる根拠のない、辻つま合せのもので、一説には第1次世界大戦の英国商船の被害を参考にしたものであったと言われている。次の表は、各年度毎の喪失量を示したものである。
      各年度の船舶喪失量 （機帆船、漁船は除く ）
    | 年度       | 隻数        | 船腹量         |
    | 昭和１６年 | ９隻        | ５万総トン     |
    | 昭和１７年 | ２０４隻    | ８９万総トン   |
    | 昭和１８年 | ４２６隻    | １６７万総トン |
    | 昭和１９年 | １,００９隻 | ３６９万総トン |
    | 昭和２０年 | ７４６隻    | １７２万総トン |
    | 合計       | ２,３９４隻 | ８０２万総トン |
    ４ ここに至って初めて軍は、海上輸送の重大さを認識し、海軍は輸送船護衛強化策として昭和18年11月　「海上護衛司令部」　を設け、海防艦の緊急建造に乗り出した。
       また、陸軍は宇品の暁部隊で徴用船護衛のため、船舶砲兵隊の強化に乗り出した。しかし、これ等の諸対策は既に手遅れで、輸送船の喪失を食い止めることは出来なかった。
    ５ 喪失商船の補充として、陸海軍ともに小型の機帆船の徴用や大量建造を行い、漁船も輸送のために徴用した。これ等の船舶も商船同様その殆どが壊滅した。
    ６ 漁船については、開戦と同時に洋上監視を目的として　「特設艦視艇」　として400隻をこえる船が海軍によって徴用された。
       昭和17年4月18日、米空母からドーリットル指揮によるB25中型爆撃機の東京初空襲をいち早く通報したのは、徴用漁船第23日東丸であった。この船は、海軍司令部に6通の敵情報を送った後、30分後に敵機により撃沈され全員が戦死した。
    ７ 商船について沈没原因を数字で見ると、第1が潜水艦の魚雷攻撃によるもので、1,153隻これは総トン数で約60％、第2が空爆によるもので902隻、次に触雷が250隻、砲撃その他が89隻となっており、わが国の海上輸送は潜水艦の雷撃により破壊され、空爆によって止めを刺されたとも言える。

* <2022-04-26 Tue>
  + 文次郎とななみ
    コンクリートで建造されてまもない桝丸橋を渡ってすぐに三叉があってその突き当たりに畑がひろがっていた。
    一人の細みの男がその三叉路を右に折れかかっていた。
    畑には数人の若い娘が枝豆を採取していた。
    その一人に男が中音のよく通る声で話しかけた。
    「おじょうさん、生が出るね」
    ななみは、喉の奥に笑い声が輝いているような優しい声に、はっとして声の主を見上げた。
    「こんにちは。じゃっど。」
    男はカーキ色のズボンに脚絆を巻いた半長靴に同じくカーキ色のジャケットを着ていた。
    この復員姿の男は笑い声を増して鹿児島から来たのかと尋ねた。
    ななみはじゃっどをつけると鹿児島出身と思われると思っていたのでしめたとしたり顔で、
    そうだと答えた。
    太平洋戦争末期になると海運を生命線としている日本の運送船の重要度は増して、その分
    潜水艦による魚雷や空爆などの攻撃は容赦無く、多くの輸送船が北、西、南太平洋の海の藻屑と化していた。
    そんな深刻な状況の中、文次郎も運送船に乗っていた。
    そしてまさに帰還できたということは奇跡に等しかった。
    文次郎は月の復員した日、つまり老いた母にふたたび会えた日に、平家由来の宗像に伝わるひらとも様に参ることを月課としていた。
    ひらとも様とは宗像の小高い数十メートルの山の頂きに設けられた石作りの社で平家由来とされるが
    その真偽は定かではなくよく地方に点在する言い伝えの類だった。
    武将を冠しているため出征の折には参る者も多く薪を集める目的もあって山道はよく整備されていた。
    文次郎もその習わしにしたがって出征の前日にひらとも様に登っていた。
* <2022-04-27 Wed>
  + コンクリート制の桝丸橋の建造は昭和47年だった
* <2022-05-08 Sun>
  + 文次郎とななみ
    杉の丸太を大井川の流れに逆らって縦に組みその横に細い枝を敷き詰め上に杉の葉と赤土をこねた粘土で塞ぐ簡易な構造の桝丸橋がある。
    自動車も通ことができるが揺れは響いていつかは破壊されてしまうほど不安な橋だ。
    大井川は護岸がほとんどされておらず大井川に寄り添って上流につづく道路の横には朽ちて
    ところどころ折れたり穴がほげている桜が奥へと点在していた。
    この時は綺麗に大井川に落ちた桜の花びらは先日の雨の日の川の流れが多数を下流へとながし
    茅や植物の隙間に残骸を残しているだけだった。
    橋には欄干させなく軋む音と詰めた赤土が水面へと落ちる音がしていた。
    その橋を渡ってすぐに三叉があってその突き当たりに畑がひろがっていた。
    一人の細みの男がその三叉路を右に折れかかっていた。
    畑には数人の若い娘が枝豆を採取していた。
    その一人に男が中音のよく通る声で話しかけた。
    「おじょうさん、生が出るね」
    ななみは、喉の奥に笑い声が輝いているような優しい声に、はっとして声の主を見上げた。
    「こんにちは。じゃっど。」
    男はカーキ色のズボンに脚絆を巻いた半長靴に同じくカーキ色のジャケットを着ていた。
    この復員姿の男は笑い声を増して鹿児島から来たのかと尋ねた。
    ななみはじゃっどをつけると鹿児島出身と思われると思っていたのでしめたとしたり顔で、
    そうだと答えた。
    太平洋戦争末期になると海運を生命線としている日本の運送船の重要度は増して、その分
    潜水艦による魚雷や空爆などの攻撃は容赦無く、多くの輸送船が北、西、南太平洋の海の藻屑と化していた。
    そんな深刻な状況の中、文次郎も運送船に乗っていた。
    そしてまさに帰還できたということは奇跡に等しかった。
    文次郎は月の復員した日、つまり老いた母にふたたび会えた日に、平家由来の宗像に伝わるひらとも様に参ることを月課としていた。
    ひらとも様とは宗像の小高い数十メートルの山の頂きに設けられた石作りの社で平家由来とされるが
    その真偽は定かではなくよく地方に点在する言い伝えの類だった。
    武将を冠しているため出征の折には参る者も多く薪を集める目的もあって山道はよく整備されていた。
    文次郎もその習わしにしたがって出征の前日にひらとも様に登っていた。

* <2022-05-16 Mon> 文次郎とななみ
  + 文次郎とななみ
    杉の丸太を大井川の流れに逆らって縦に組み湿らした蔓を叩いてそれを回して吊り上げ、その横に細い枝を敷き詰め上に杉の葉と赤土をこねた粘土で塞ぐ簡易な構造の桝丸橋がある。
    掛けた櫓は都合４本岸の２本と中の２本それが杉の丸太の重みと赤土でなんとか持つだろうという近くの一杯飲みの土建屋の指示
    で掛けたのだ、土建屋は重けりゃ重いほど強いと威張り散らしていた。
    自動車も通ることができるが揺れは響いていつかは破壊されてしまうほど不安な橋だ。
    案の定次の年の台風でこの橋はなくなった。
    大井川は護岸の整備がほとんどされておらず川に寄り添って上流につづく道路の横には朽ちて
    ところどころに折れたり穴がほげている桜の並木が奥へと点在していた。
    この時だけは綺麗に大井川に落ちた桜の花びらは先日の雨の日の川の流れが多数を下流へとながし
    茅や植物の隙間に残骸を残しているだけだった。
    橋には欄干に軋む音と詰めた赤土が水面へと落ちる音がしていた。
    左手にはよく開墾の跡が見える田畑が低山の懐に入る様相を示していた。
    その橋を渡ってすぐに三叉路があってその突き当たりに畑がひろがっていた。
    一人の細みの男がその三叉路を右に折れかかっていた。
    畑には数人の若い娘が絹サヤを採取していた。
    一番近くの黄色い農作業帽子をしめた娘に男の中音の橋に笑い声が輝くようなよく通る声で話しかけた。
    「おじょうさん、生が出るね」
    ななみは、喉の奥にやさしい輝く笑い声がすうっと流れてきて、声の主を見上げた。
    「こんにちは。じゃっど！」
    男はカーキ色のズボンに脚絆を巻いた半長靴に同じくカーキ色のジャケットを着ていた。
    この復員姿の男は笑い声を増して鹿児島から来たのかと尋ねた。
    ななみはじゃっどをつけると鹿児島出身と思われると思っていたのでしめたとしたり顔で、
    じゃっどと答えた。
    太平洋戦争の末期になると海運を生命線としている日本の運送船の重要度は増して、その分
    潜水艦による魚雷や空爆などの攻撃は容赦無く、多くの輸送船が北、西、南太平洋の海の藻屑と化していた。
    そんな深刻な状況の中、
    文次郎も運送船に乗っていた。
    そしてまさに帰還できたということは奇跡に等しかった。
    文次郎は月の復員した日、つまり老いた母にふたたび会えた日に、平家由来の宗像に伝わるひらとも様に参ることを月課としていた。
    平和(ひらとも)さまと和宗(ともむね)さまは大井に残る平家落武者伝説を謂れとしている。
    平家が壇ノ浦の合戦に破れ一門の平和(ひらとも)様と知宗(ともむね)様もこの宗像の里まで落ち延びてきた。
    幾日か詫びしい里山の奥の暮らしをしていたがある時源氏の追手が現れた。
    用山と大井の低山の境に逃がれた平和(ひらとも)様は眼下に源氏の白旗が田畑になびくをみて「今日限りの命ぞ」と観念して潔く自害された。
    同じく知宗(ともむね)様は大井と田島の境で自害された。
    里の人々はこの二人の武将を菩提をともらってそれぞれに石祠を建てて祀っている。
    武将を冠しているため出征の折には参る者も多く、薪を集める目的もあって山道はよく整備されていた。
    文次郎もその習わしにしたがって出征の前日にひらとも様に登っていた.
    じゃっど。その響にはかつて死んでいった同胞を思い起こし、ただうなずける、その
    娘の可愛さに、自分の境遇と自分の今していることのなんの射線もないので、
    文次郎はななみに、一緒にひらとも様にのぼるかと言った。
    ななみは文次郎の人格に慈しみに近い安心感のような懐かしみのようなものを感じた。
    だからその文次郎の正当な理由のひらとも様に一緒に登ると言った。
    ななみは部屋に駆け戻って急いで支度をすませて戻ってきた、手にはここではカメラで通っている携帯を油紙に包んでもってきた。
    文次郎はやさしく背中を推して名もなき低山の登口への道へ二人は入って行った。
    薪とりでゆるいよく整備された山肌は登りやすかった。
    ひらとも様までほんの１０分も登ったところで着いてしまった、小さな石造りの祠が二つ横に並んでその中には福神売りが
    押し付けて邪魔になった紙粘土の恵比寿様やらが沢山置いてあった、どれがひらとも様なのかわからないななみは文次郎に尋ねたが
    文次郎も知らなかった。
    私のかあちゃんもしらんやろうなとも言った。
    ななみは文次郎の合唱が終わるのを見計らって持ってきた油紙に大事に包んだ携帯を福神の恵比寿様で隠すようにおいた。
    携帯のバッテリーの残量は10%を切っていたがいつかなんかの役に立つのではと思っていた。
    文次郎は山を下りながら母は若い時事故で失明し片目がないと伝えた、本村橋の永井さんの母と仲が良く毎日遊びに行っている
    でもそこの二人の兄弟にはどうも嫌われているようだとも言った、例の乞食兄弟のことだ。
    特に弟にはほうきを逆さに置いて早く帰れといじめられているらしい。
    そういうと文次郎の笑い声が木々の間の空に舞い上がった。
    これはカツオのことだ。
    そう思った時出太鼓の音が三度ひびいて、1日の作業の終わりを告げていた。

* <2022-06-09 Thu>
  + ばあさんの梅干し
    + 2021年は5/24に3升,一晩アク抜き,450gの塩で梅酢作った
      この塩の算出の元になったのが2019/8/7 にばあさん本人から聞いたことをスマホのメモにしていた
      以下の内容からだったと忘れていたがそうだと思う。
      + memo の中
        6月,梅採取,一晩水につけてアク抜き,一升,８寸
      + 一升,８寸はばあさんが繰り返し言ってた言葉、それをもとに調べて１升150gの塩と算出したっぽい
      + だから３升450gだ、８寸は180の80%的意味合いだったか。
      + 実際これで去年梅酢漬けが成功している
    + 実はこの塩分濃度一般(長谷川さんの奥さんにも聞いたら)
      梅1kg->塩180g->焼酎25ccとメモをもらったので一般は梅の18%にするということなのでぴったし。
    + ところがばあさんの梅干しは一般が一升換算324gのところ150gと半分以下の塩分濃度なんだ
    + じいさんはおれの作った梅干しはばあさんのうめぼしじゃないといって死んでいった
  + ばあさんの梅干し塩判明
    + 一升,８寸は、立法寸のことで8/64.8272=0.123405となる
    + 1800*0.123405=222.129が一升あたりの塩の重さとなる
* <2022-06-17 Fri>
  + 中村家のばあさんは田植え後カエルがうるさいと警察にでんわしてカエルはあんたより
    昔からいるもんだからどうしようもないんだよ。
    とかいわれたらしい。
* <2022-07-01 Fri>
  + 深田図書館
    + 宗像むかしの生活研究1むかしの子どもの学校生活と遊び
      + 昭和7年弁当箱はアルミニウムおかずは梅干しらっきょう漬物が主体、時にかまぼこや天ぷら
      + 女の子の遊びに手毬つきがあるので７才のたえこといっしょにしょうこが寝ている清和背負って遊んでいる
      + 1960年代からの高度成長による変化
      + おかしとして家になったくだものが主だったが、はったい粉(麦を炒って石臼でひいたもの)
      + 妊婦は腹がせきだすまで、つくまみこむまで働き続けた、仕事中少々腹がせいてもおさまるまって仕事を続けた
      + ぎゅうたらしゅう(仰山)に言うのをはずかしがった
      + たいてい村にはひとりかふたりの産婆さんがいた
      + 妊娠６ヶ月ころにしりもちをついたら姑さんが「そりゃでるばい、はよう黒砂糖馬たべときない」といわれたくさん
        食べた、流産せんおまじない
      + あんたがたどこさ　肥後さ、肥後どこさ　熊本さ、熊本どこさ　えんばさ、えんばどこゆきや　たぬきがおってさ、
        それを漁師が　鉄砲で打ってさ、煮てさ　焼いてさ　食ってさ、うまさのさっさ
        と叫んでまだ茅葺の母家の屋根にシュートを放った、それがバスケットの見事なシュートだったのであぜんとしたたえこ
        は泣き出すのを堪えようとしていた。
        それを縁側から見ていた姑の笑い声がみんなを振り向かせて笑わせた。
        たえこだけが笑わなかった。
      + おきうと、おきうと草を水にさらして、ごみをとり、干し、湯にもどして炊き、煮溶かして、最後に酢を少量いれて、火おとめて
        よくねり型にながして硬め、胡麻醤油でたべる。

* <2022-08-28 Sun>
  + 千恵美さんからlineで静子おばちゃんが朝2:00夏バテかなで運んだが心臓が
    悪くてそのまま亡くなったとの連絡。
  + 昨晩名古屋のおじさんのところへ静子おばちゃんが知らせにきて、じいちゃん一人
    になったなあといったそうです。
    合わせて昌子は?とも恵子さんが昌子さんは亡くなったでしょう。と答えたらしい。
  + 私には静子おばちゃんといつも一緒にいる昌子がいないのでしょうこは?といったと
    思った。
  + この度は静子叔母様のご冥福を心よりお祈りいたします。
    和幸様、みどり様、健二様、ご家族様のご心労ご察しいたします。
    通夜、告別式などお忙しいことと思いますので一筆にて失礼します。
    
    昨年偶然に静子叔母様と電話で話を伺えたのがほんとうによかった。

    母の位牌を持って鹿児島参りをしたいと思いながら、もう一度お話をしたいと
    思っていましたが、ついに果たせませんでした。
    母昌子と静子叔母様が福岡の宗像市で働いていた頃を何かしら記憶
    に残そうとしているので残念ですが、何か形にはしたいと思います。

    皆様、くれぐれも心落としないよう御体をご自愛ください。

    永井 利一
