* <2022-09-02 金> 1. 鹿児島から福岡
  
  　昭和30年5月。午前6時50分。
  普通快速、鹿児島始発20時30分、門司港行きが、しずこの待つ東郷駅に、
  鹿児島本線上りの難所である白水峠の下りを利用し安堵の白煙を吹上げ、
  ホームには水蒸気の渦を撒きながら入線してきた。

  　そして汽笛がこの５月のよく透き通った青い空を震えさせた。

  　駅の隅には花壇が整備されていてもうツツジの花の淡い朱色をチラつかせている。
  機関車は現在も残る宗像大社の白い宣伝塔を横にみてぴたりと停車し、同時に連結の音を立てた。
  手動の乗降扉を開け眩しい空をあおぎながら客たちが降りてきた。

  　一番ホームの横に建てられた駅舎はガラス張りの木窓が薄く貼り付けられ中央と左右が
  入口と出口と一緒の改札の駅員がこちらを向いて小さなおかっぱ頭の少女に
  目配せをして案内をさせようとしていた。

  　少女は大きな風呂敷を首に回し、10時間の長い汽車の旅で顔いっぱいに煤をつけていた。
  煤のない細い目の周りだけを点滅させてあたりをおどおどと見回しながら
  やっとのことでいっちょうらのワンピースのポケットから探し出した切符を駅員に手渡した。
  このワンピースの柄は前面は煤で汚れ、座っていたため背中と尻が白地の花柄だと初めてわかった。

  　駅員の改札パンチのカチカチ音の小気味良い音をすぎて待合椅子のならぶ
  駅舎に入るなり「しょっこちゃんこっちこっち」と若い女の声がした。
  そこには妹を福岡まで呼びよせた姉のしずこが待っていた。
  「がんばったね、よくきたね」しずこは妹の荷物をやさしく抱いてうけとった。
  姉は待合椅子に妹を座らせ手拭いで本人も気づいていない顔いっぱいの煤を拭いてやった。 
       
  　東郷駅のある宗像は黒田藩御用金鉱が全盛期だったため町には活気があった。
  というよりは金鉱は隠蔽され地元住民もしらないものが多かった。
  むしろ庶民には炭鉱が大井と池野に二つあったことによるものが大きかった。
  太平洋戦争当時から、戦況の不利が見え始め内需拡大政策から炭鉱開発への補助金
  目当てに大井炭鉱も開発され宇部興産の資本と人員が入り込んでいた。
  その炭坑夫の落とす金を目的に居酒屋やカフェーの類もちらほら見受けられ
  町では流行りの映画館も数件あった。

  　当時鉄道で鹿児島から福岡にくるには３つの方法があった。
  一つは夜行列車急行さつま東京行き、鹿児島発23時30分、博多到着7時07分。
  二つ目が同じく夜行列車急行霧島東京行き、鹿児島発20時30分、博多到着5時09分である。
  そして三つ目が普通快速門司港行きである。
  当時は急行しかなく乗り継ぎ時間を考えると各停しかとまらない東郷駅などに向かう
  には急行券のいらない普通快速はコスパにもすぐれ老若男女問わず人気があった。

  　特急の運行は1958年まで待つことになる、有名な特急はやぶさは鹿児島博多間を
  6時間半に大幅に短縮した。
  しょうこは里帰りなどで帰郷する場合は特急はやぶさを利用することになるが
  私が母に聞いたいた6時間半という数字は普通快速の10時間20分の記憶をいつしか塗り替えた
  のだろうと推測する。

  　二人がいる駅の北側は緩い下り道となっていてその先まで商店がならんでいた。
  二人はバスの時間を確かめた後、待ち時間の間にうどんを啜ることにした。
  駅舎のうどん屋は立ち食いだったが北九州では評判のよい東筑軒がやっていた。
  姉はかしわうどんを二つたのんで置いてあるやかんから湯呑みにお茶をついだ。
  「よくきたね、つかれたやろう」
  妹のしょうこは気丈に答えた
  「そうでもなかったけど博多駅の乗り換えで迷った」
  しばらくしてうどんが目の前にでてきた。
  しずこは「こしゅ(とうがらし)をこっちじゃ'こしょう'って言うんよ」と
  いいながら一振り妹のうどんにかけてやった。
  しょうこはかしわの匂いに少しけげんさを抱いたがこれが美味しいんだと
  改めて異郷にきたことをかき消すようにをうどんをすくった。
  横にいる姉と何ヶ月ぶりかに一緒に食べることことがうどんをすくうたびに
  嬉しさにかわっていった。
  そして不安の胃に流し込むうどんにみたされて、
  うまれてはじめて一人で乗った汽車の出来事を振り返った。
