* <2021-02-28 Sun> 9. おなご衆

  　しずこは昼食の支度に人がいらないのでしょうこの挨拶が済ませてすぐに八百重屋敷を出た。

  そこに牛や鶏の世話をしているおとこ衆に用山に帰ると告げて、

  時折ダンプがすれ違い、そのダンプの掘った凸凹した道を歩いていた。

  　途中に例の乞食兄弟の家の横をとおった。

  あらためてみるとこの家は結構長い。

  牛小屋から始まり、いなやから風呂とクドと土間1と食場そして敷居があって座敷がある。

  座敷は３つ道路沿いに続いて最後に焚物小屋がその集めた薪をあましている。

  ガラス格子の枠は所々折れてガラスもヒビが入って割れている中は外からでも雑然として片付けができていないのがよくわかる。

  玄関は２枚の引き戸になっているが、なんだか傾いている。

  そして最後に斜めに落ちる階段があってその横に狭い庭がある。

  その庭はとても小さいがよく剪定された松や牧の木などがありところどころに花咲かせた優しさを訴える植物が散りばめられている。

  次元の違う世界がこの小さな坂に造られている。

  よく配置され階段の段々の降り先に小さな池まで見えた、こんな小さな空間にどれだけの努力でこの庭を維持しているのだろうか。

  その庭を見下ろして足を止めて見たが周りの人の目が気になって止めて帰路を急いだ。

  　用山まで小一時間だが山を登らないといけないが庭の横には雑貨屋がある、この家は道に沿って長く張り付くのではなく逆に垂直に伸びる家ここは炭鉱の元締めと荒い子分の休む場所になっている。

  　まだ人気はないので安心して横をすぎてまだ川沿いの道をいく。

  　川の流れはすこし厳しくなって左側は崖が張り出し、しがみついている木々が川を覆ってその下の流れが右へと蛇行して用山の山の中へと入り込んでいる。

  ここを中左に折れて緩い山道に入る、山道はうっすら暗闇の帷をおろしている。

  　この難所を過ぎればまた左に折れて川沿いに戻り木造の５間ほどの橋をわたる。

  そうすればしずこのが奉公している屋敷の屋根が見える。

  しずこが奉公する屋敷はやまだ家で用山の部落では一番立派な通り門を備えている。

  この屋敷は黒栖様を祀っている山の麓にある。

  通り門は門の左右上部がいな屋か住居になっておりその下の空間を人や荷馬車が通るようになっている門のことである。

  　前方には北西に広がる刈田の平野でも日の光さしてきてが暖かさを広げてがっていた。

  ここまできて安心したので妹のしょうこのことを考えた。

  　私は1934年生まれの戌年、しょうこは３つ下の1937年丑年。干支はこどもの頃から

  そういう性格なんだと思っていた私はいつもキャンキャン騒いでいるしるし、しょうこ

  はおっとりしている。だから中学を出ても母ちゃんの横で家事手伝いやら兄たちの世話をしているのではこれでは先がないと思って福岡に誘って世間を教えてあげなければ
  と決心してそれが昨日実現した。

  　だがかわいい妹の人生に関わったことがどうなるのか。もうなんども考えたがそれがいいと思ったからそれでいいとまた納得した。

  やまだの屋敷に帰りついた。大きな声で挨拶をして部屋へあがろうとしたら最近色目を使ってきているおとこ衆の一人が声をかけてきた。

  「どうだった妹は無事についか。橋をわたるのがみえたよ。妹はこっちに連れてきてないんだ。どんな妹なんだ。」

  しずこはこの男が嫌いだったので「お前には関係ねー。かつよさんはどこにいる？」

  女主人に話をしたかった。「ふん。子供の世話で部屋にいるよ。」

  部屋に戻っていつもの支度をしてクド場にいって水をしゃくっていっぱいのんだ。

  主人の部屋の奥にすり足でいって障子越しに「しずこです、ただいま帰りました。」

  女主人の反応は少し遅れて「妹さんは無事に坂屋敷についたんだね。」

  しずこは答えた。

 「それがもうひとりいとこを連れてきたんです。ひとつ二つ下ですから１７歳くらいです。」

  こどもをあやしながらいった。

  「おなごしはどこでも必要だからいいんだけど親御さんはわかってらっしゃるのかい。」

  しずこはななみの人柄には不思議な安心があったので「それは大丈夫です。

  明日は朝の仕事終わったらもう一度大井にいってきます。」と答えた。

  女主人に今日は下の女の子がぐづついているので一緒に昼寝してくれと言われた。

  クド場にもどると他のおなご衆は妹といとこがきたことをしっていた。

  あいつが立ち聞きしていたらしい。

  この日女のあかちゃんを抱いて４人で眠った。あかちゃんは数えの２つだった。

  しずこはなんども夜泣きで起こされその都度他のおなご衆にもんくをいわれた。

  この赤ちゃんは他のおなご衆には懐かなかった、しずこの子守唄にだけ安らかな顔でねた。

  しずこの子守唄はおはら節だった。

  　　　　　花は霧島

  　　　　　煙草は国分

  　　　　　燃えて上がるは桜島

  　　　　　　　桜島には霞がかかる

  　　　　　　　わたしゃ おはんに気がかかる

  　　　　　咲いた桜に つなぐな駒を

  　　　　　駒がいさめば花が散る

  　　　　　　　みえたみえたよ 松原越しに

  　　　　　　　丸に十の字の帆が見えた

