* <2022-09-02 金> 2. 朝の回想

	 今朝はいつもの鶏が騒ぎ出す前に薄暗い障子越の光と共に母親の手で起こされた。
	 眠いのと昨日兄たちの別れの宴で舞い上がり調子にのったのを悔いた倦怠で母
	 を見起こしたがもう姉のもとにいくことは決心の絶対としていたので諦めて
	 腕でまぶたを拭いた。
	 母はいつもより早めに起きて朝のめざめの味噌汁の匂いを子供たちに与えていた。
	 しょうこは起きて自分の役目である弟を探した。
	 足元に布団をはみ出し、身勝手な足を布団からはみ出し、服従の印の
	 しょうこの足のにおいをかいでるらしいさちおがいた。
	 このかわいい弟は今日限りすべてから解放され男としていきてゆく。
	 やっぱりやめたい。さちおがいるからここにいたいと叫びたかったがもうもどれない。
	 そして別れが来た、しょうこは涙を流さなかった、母ちゃんは涙を浮かべていたが
	 長兄がしきりをしていた、しずこがいるしだれもがしょうこの幸福を疑わなかった。
	 ただ、さちおだけはその別れの意味を切実に惜しんでいた。

	 しょうこは長兄と二人の最寄りの日豊本線の加治木駅へと向かうことになった。
         長兄はこれからの長旅を考えて加治木に向かう煙草を運ぶ牛車に乗せてもらう
         算段をしていた待ち合わせは役場の前だった。
         ふたりは役場前まで歩いた、しょうこの荷物は着物と着替えなどをいれる
         と風呂敷に大つつみとなった。それをもって兄は末妹のためその未来を信じて歩いた。
         牛車はまだついてはなかったが程なく牛のなく声とともにやってきた。
         牛車での10kmの道のりは5時に出発して２時間を超えて7時をまわっていた。
         ??? 当時でも路線バスが溝辺-加治木(14.5kn)(日豊本線),溝辺-嘉例川(4km)(肥薩線)で運行しているので書き換える方がいいかも　3/21
         
	 定刻通り西鹿児島への汽車を確認してしょうこの土産のカルカンを買って
	 しょうこの風呂敷に入れてやった。
	 「しょうこよ。ぜったい、くじけて帰ってくるんじゃないよ、頑張ってな。」
	 しょうこは兄の言葉を心に刻んだ。
	 西鹿児島までは小一時間で着いた。
	 鹿児島本線の特急かいもん博多門司ゆきはあと３０分後だった。
	 この西鹿児島駅では大きな風呂敷を抱えた若い女は珍しい光景ではなかった。

	 しかし、しょうこは今朝母ちゃんが握ってくれたにぎりめしと高菜の漬物に水筒だけが頼りだった。
	 このひとりで福岡に何時間も客車に乗って頑張れるんだろうか、便所をなんども
	 行き来して待った。
	 にぎりめしと高菜の漬物に水筒。水筒は２番目のにいちゃんの自慢の水筒だった。
	 溝辺の水をいれているんで死ぬまで飲むなと冗談を言われていた。
	 死ぬ間際に飲むと溝辺に戻って帰ってこれるよ。
	 そうも言われていた。
