* <2021-02-28 Sun>  5. 八尾重屋敷

  　３人の乗るバスは東郷駅についていて出発の時刻を待っていた。
  
  ３人が乗ると車掌が妹の大きな風呂敷を取って空いている席においた。

  車掌は手についた煤に眉をひそめて払い次の乗客を見下ろした。

  その先には見たこともない紺の制服らしきものを着た少女がいかつい目で見上げた。

  車掌は肩からかけたガマ口の銀のつかみでを撫でてそれをいなした。

  少女に切符を切ってバスの後部に促した。

  そのあと車掌は乗客を数人乗せて切符を切ると運転手に促したのち車掌席に座った。

  姉妹と少女は仲良よさそうに席に座ったていた。

  運転手は何かを呟いて、鼻の突き出たバスのセルをキュルキュルと回してエンジンを起こした。

  ３人を乗せたバスは東郷駅から商店街をくだって左に大きな池を左に見て山中へと

  入ろう坂を登り始めると右手には羽色のコンクリートが低木の茂みから見え隠れして

  何やら建物があるのがわかった。

 「あれは避病院といって伝染病患者がはいっている病院よ。あそこには絶対入らなでよ。」

  姉は３つ年下の妹の怖気を面白がっていった。

  左手の山の中腹に小さな池をみてバスは迂回しようとしていた時姉はまた続けた。

 「あの池向こうに煙突がみえるでしょう。あれは火葬場よ。」

  妹は不安になり前席の黒いバーを握りしめた。

  ななみはその妹の手をつついて硬さを確かめていた。

  バスは火葬場と避病院の横を抜けるゆっくりと下りだし避病院をすぎて手付かずの低木

  が茂山には爽快な新緑をまとっていた。

  左方の広葉樹の山も新緑が広がっていたがバス道から横に走る砂利道数本あり

  民家の存在を予見していたしょうこは果たして自分がこれから世話になる家が

  いつ出現するのか期待が湧いてくるのを感じた。

  バス道はいよいよ下り坂が急になり両脇の山が開けるのと同時に一本のまっすぐの

  道になった時両脇に刈田が大きく開いて周りに集落があるのを見た時ここがこれから

  生活していくところとわかった。

  バスは直線が終わり右に直角に曲がったところで停車した、姉は妹についたことを肩で教えた。

  車掌に風呂敷荷物をもってもらいながら３人はバス停に降りた。

  車掌はななみに荷物がないから、なお風呂敷が重いものだと決め付けていた。

  バス停の横には川幅は5m程のちいさな川ながれていて、その横に道が上流へと続いて、

  もうすでに葉桜となった桜の並木が少しきつくなった日差しの木漏れ日をじゃりの

  道に現していた。

  ３人は程なく木造の見窄らしい橋をわたった。

  前方にはゆるい坂を登ったところに屋敷があり、それから視線を右に落とすと

  大きな茅葺の屋根の屋敷と納屋、そして道沿い小さな茅葺の家もあった。

  姉は妹にその右の大きな屋敷を指差して止めた。

 「あそこの屋敷で仕事するんよ」

  橋を渡るとすぐに二股にわかれそのどちらにも集落が続いていた、道に挟まれたところは畑になっていて

  竹で編んだようなものに植物が絡んでいて実をむすんでいるようだった。

  姉が指差した左側に屋敷があり正面の納屋や小屋があったそこまで玄関道が続いて両方にも畑が

  あって白菜などの葉物が植えられていた。

  を正面に右にいなやとよばれる作業倉庫

  があった。そこには見たこともない吹子などが格納されてその端には牛小屋があり

  庭の端には鶏小屋があった。

  牛と鶏の糞尿の匂いは無風の中でも帯が閃くように漂っていた。
